package modelo;
// Generated 15 jun. 2021 21:58:49 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Armadura generated by hbm2java
 */
@Entity
@Table(name = "armadura", catalog = "anima_sheets_data")
public class Armadura implements java.io.Serializable {

	private Integer idArmadura;
	private String nombre;
	private int requisitoNecesario;
	private int restriccionMovimiento;
	private int tipoArmaduraFilo;
	private int tipoArmaduraContundente;
	private int tipoArmaduraPenetrante;
	private int tipoArmaduraCalor;
	private int tipoArmaduraElectrico;
	private int tipoArmaduraFrio;
	private int tipoArmaduraEnergia;
	private int entereza;
	private int presencia;
	private int penalizadorNatural;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public Armadura() {
	}

	public Armadura(String nombre, int requisitoNecesario, int restriccionMovimiento, int tipoArmaduraFilo,
			int tipoArmaduraContundente, int tipoArmaduraPenetrante, int tipoArmaduraCalor, int tipoArmaduraElectrico,
			int tipoArmaduraFrio, int tipoArmaduraEnergia, int entereza, int presencia, int penalizadorNatural) {
		this.nombre = nombre;
		this.requisitoNecesario = requisitoNecesario;
		this.restriccionMovimiento = restriccionMovimiento;
		this.tipoArmaduraFilo = tipoArmaduraFilo;
		this.tipoArmaduraContundente = tipoArmaduraContundente;
		this.tipoArmaduraPenetrante = tipoArmaduraPenetrante;
		this.tipoArmaduraCalor = tipoArmaduraCalor;
		this.tipoArmaduraElectrico = tipoArmaduraElectrico;
		this.tipoArmaduraFrio = tipoArmaduraFrio;
		this.tipoArmaduraEnergia = tipoArmaduraEnergia;
		this.entereza = entereza;
		this.presencia = presencia;
		this.penalizadorNatural = penalizadorNatural;
	}

	public Armadura(String nombre, int requisitoNecesario, int restriccionMovimiento, int tipoArmaduraFilo,
			int tipoArmaduraContundente, int tipoArmaduraPenetrante, int tipoArmaduraCalor, int tipoArmaduraElectrico,
			int tipoArmaduraFrio, int tipoArmaduraEnergia, int entereza, int presencia, int penalizadorNatural,
			Set<Personaje> personajes) {
		this.nombre = nombre;
		this.requisitoNecesario = requisitoNecesario;
		this.restriccionMovimiento = restriccionMovimiento;
		this.tipoArmaduraFilo = tipoArmaduraFilo;
		this.tipoArmaduraContundente = tipoArmaduraContundente;
		this.tipoArmaduraPenetrante = tipoArmaduraPenetrante;
		this.tipoArmaduraCalor = tipoArmaduraCalor;
		this.tipoArmaduraElectrico = tipoArmaduraElectrico;
		this.tipoArmaduraFrio = tipoArmaduraFrio;
		this.tipoArmaduraEnergia = tipoArmaduraEnergia;
		this.entereza = entereza;
		this.presencia = presencia;
		this.penalizadorNatural = penalizadorNatural;
		this.personajes = personajes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ARMADURA", unique = true, nullable = false)
	public Integer getIdArmadura() {
		return this.idArmadura;
	}

	public void setIdArmadura(Integer idArmadura) {
		this.idArmadura = idArmadura;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "REQUISITO_NECESARIO", nullable = false)
	public int getRequisitoNecesario() {
		return this.requisitoNecesario;
	}

	public void setRequisitoNecesario(int requisitoNecesario) {
		this.requisitoNecesario = requisitoNecesario;
	}

	@Column(name = "RESTRICCION_MOVIMIENTO", nullable = false)
	public int getRestriccionMovimiento() {
		return this.restriccionMovimiento;
	}

	public void setRestriccionMovimiento(int restriccionMovimiento) {
		this.restriccionMovimiento = restriccionMovimiento;
	}

	@Column(name = "TIPO_ARMADURA_FILO", nullable = false)
	public int getTipoArmaduraFilo() {
		return this.tipoArmaduraFilo;
	}

	public void setTipoArmaduraFilo(int tipoArmaduraFilo) {
		this.tipoArmaduraFilo = tipoArmaduraFilo;
	}

	@Column(name = "TIPO_ARMADURA_CONTUNDENTE", nullable = false)
	public int getTipoArmaduraContundente() {
		return this.tipoArmaduraContundente;
	}

	public void setTipoArmaduraContundente(int tipoArmaduraContundente) {
		this.tipoArmaduraContundente = tipoArmaduraContundente;
	}

	@Column(name = "TIPO_ARMADURA_PENETRANTE", nullable = false)
	public int getTipoArmaduraPenetrante() {
		return this.tipoArmaduraPenetrante;
	}

	public void setTipoArmaduraPenetrante(int tipoArmaduraPenetrante) {
		this.tipoArmaduraPenetrante = tipoArmaduraPenetrante;
	}

	@Column(name = "TIPO_ARMADURA_CALOR", nullable = false)
	public int getTipoArmaduraCalor() {
		return this.tipoArmaduraCalor;
	}

	public void setTipoArmaduraCalor(int tipoArmaduraCalor) {
		this.tipoArmaduraCalor = tipoArmaduraCalor;
	}

	@Column(name = "TIPO_ARMADURA_ELECTRICO", nullable = false)
	public int getTipoArmaduraElectrico() {
		return this.tipoArmaduraElectrico;
	}

	public void setTipoArmaduraElectrico(int tipoArmaduraElectrico) {
		this.tipoArmaduraElectrico = tipoArmaduraElectrico;
	}

	@Column(name = "TIPO_ARMADURA_FRIO", nullable = false)
	public int getTipoArmaduraFrio() {
		return this.tipoArmaduraFrio;
	}

	public void setTipoArmaduraFrio(int tipoArmaduraFrio) {
		this.tipoArmaduraFrio = tipoArmaduraFrio;
	}

	@Column(name = "TIPO_ARMADURA_ENERGIA", nullable = false)
	public int getTipoArmaduraEnergia() {
		return this.tipoArmaduraEnergia;
	}

	public void setTipoArmaduraEnergia(int tipoArmaduraEnergia) {
		this.tipoArmaduraEnergia = tipoArmaduraEnergia;
	}

	@Column(name = "ENTEREZA", nullable = false)
	public int getEntereza() {
		return this.entereza;
	}

	public void setEntereza(int entereza) {
		this.entereza = entereza;
	}

	@Column(name = "PRESENCIA", nullable = false)
	public int getPresencia() {
		return this.presencia;
	}

	public void setPresencia(int presencia) {
		this.presencia = presencia;
	}

	@Column(name = "PENALIZADOR_NATURAL", nullable = false)
	public int getPenalizadorNatural() {
		return this.penalizadorNatural;
	}

	public void setPenalizadorNatural(int penalizadorNatural) {
		this.penalizadorNatural = penalizadorNatural;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "armadura_personaje", catalog = "anima_sheets_data", joinColumns = {
			@JoinColumn(name = "ID_ARMADURA", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_PERSONAJE", nullable = false, updatable = false) })
	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

}
