package modelo;
// Generated 13 jun. 2021 23:25:16 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ArteMarcial generated by hbm2java
 */
@Entity
@Table(name = "arte_marcial", catalog = "anima_sheets_data")
public class ArteMarcial implements java.io.Serializable {

	private Integer idArteMarcial;
	private String nombre;
	private String descripcion;
	private int conocimientoMarcial;
	private int bonoAtaque;
	private int bonoEsquiva;
	private int bonoParada;
	private int bonoTurno;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public ArteMarcial() {
	}

	public ArteMarcial(String nombre, String descripcion, int conocimientoMarcial, int bonoAtaque, int bonoEsquiva,
			int bonoParada, int bonoTurno) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.conocimientoMarcial = conocimientoMarcial;
		this.bonoAtaque = bonoAtaque;
		this.bonoEsquiva = bonoEsquiva;
		this.bonoParada = bonoParada;
		this.bonoTurno = bonoTurno;
	}

	public ArteMarcial(String nombre, String descripcion, int conocimientoMarcial, int bonoAtaque, int bonoEsquiva,
			int bonoParada, int bonoTurno, Set<Personaje> personajes) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.conocimientoMarcial = conocimientoMarcial;
		this.bonoAtaque = bonoAtaque;
		this.bonoEsquiva = bonoEsquiva;
		this.bonoParada = bonoParada;
		this.bonoTurno = bonoTurno;
		this.personajes = personajes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ARTE_MARCIAL", unique = true, nullable = false)
	public Integer getIdArteMarcial() {
		return this.idArteMarcial;
	}

	public void setIdArteMarcial(Integer idArteMarcial) {
		this.idArteMarcial = idArteMarcial;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "CONOCIMIENTO_MARCIAL", nullable = false)
	public int getConocimientoMarcial() {
		return this.conocimientoMarcial;
	}

	public void setConocimientoMarcial(int conocimientoMarcial) {
		this.conocimientoMarcial = conocimientoMarcial;
	}

	@Column(name = "BONO_ATAQUE", nullable = false)
	public int getBonoAtaque() {
		return this.bonoAtaque;
	}

	public void setBonoAtaque(int bonoAtaque) {
		this.bonoAtaque = bonoAtaque;
	}

	@Column(name = "BONO_ESQUIVA", nullable = false)
	public int getBonoEsquiva() {
		return this.bonoEsquiva;
	}

	public void setBonoEsquiva(int bonoEsquiva) {
		this.bonoEsquiva = bonoEsquiva;
	}

	@Column(name = "BONO_PARADA", nullable = false)
	public int getBonoParada() {
		return this.bonoParada;
	}

	public void setBonoParada(int bonoParada) {
		this.bonoParada = bonoParada;
	}

	@Column(name = "BONO_TURNO", nullable = false)
	public int getBonoTurno() {
		return this.bonoTurno;
	}

	public void setBonoTurno(int bonoTurno) {
		this.bonoTurno = bonoTurno;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tabla_arte_marcial_personaje", catalog = "anima_sheets_data", joinColumns = {
			@JoinColumn(name = "ID_ARTE_MARCIAL", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_PERSONAJE", nullable = false, updatable = false) })
	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

}
