package modelo;
// Generated 13 jun. 2021 23:25:16 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Caracteristicas generated by hbm2java
 */
@Entity
@Table(name = "caracteristicas", catalog = "anima_sheets_data")
public class Caracteristicas implements java.io.Serializable {

	private int idPersonaje;
	private Personaje personaje;
	private int agilidad;
	private int constitucion;
	private int destreza;
	private int fuerza;
	private int inteligencia;
	private int percepcion;
	private int poder;
	private int voluntad;
	private Integer agilidadTemporal;
	private Integer constitucionTemporal;
	private Integer destrezaTemporal;
	private Integer fuerzaTemporal;
	private Integer inteligenciaTemporal;
	private Integer percepcionTemporal;
	private Integer poderTemporal;
	private Integer voluntadTemporal;

	public Caracteristicas() {
	}

	public Caracteristicas(Personaje personaje, int agilidad, int constitucion, int destreza, int fuerza,
			int inteligencia, int percepcion, int poder, int voluntad) {
		this.personaje = personaje;
		this.agilidad = agilidad;
		this.constitucion = constitucion;
		this.destreza = destreza;
		this.fuerza = fuerza;
		this.inteligencia = inteligencia;
		this.percepcion = percepcion;
		this.poder = poder;
		this.voluntad = voluntad;
	}

	public Caracteristicas(Personaje personaje, int agilidad, int constitucion, int destreza, int fuerza,
			int inteligencia, int percepcion, int poder, int voluntad, Integer agilidadTemporal,
			Integer constitucionTemporal, Integer destrezaTemporal, Integer fuerzaTemporal,
			Integer inteligenciaTemporal, Integer percepcionTemporal, Integer poderTemporal, Integer voluntadTemporal) {
		this.personaje = personaje;
		this.agilidad = agilidad;
		this.constitucion = constitucion;
		this.destreza = destreza;
		this.fuerza = fuerza;
		this.inteligencia = inteligencia;
		this.percepcion = percepcion;
		this.poder = poder;
		this.voluntad = voluntad;
		this.agilidadTemporal = agilidadTemporal;
		this.constitucionTemporal = constitucionTemporal;
		this.destrezaTemporal = destrezaTemporal;
		this.fuerzaTemporal = fuerzaTemporal;
		this.inteligenciaTemporal = inteligenciaTemporal;
		this.percepcionTemporal = percepcionTemporal;
		this.poderTemporal = poderTemporal;
		this.voluntadTemporal = voluntadTemporal;
	}

	@GenericGenerator(name = "modelo.CaracteristicasIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personaje"))
	@Id
	@GeneratedValue(generator = "modelo.CaracteristicasIdGenerator")

	@Column(name = "ID_PERSONAJE", unique = true, nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personaje getPersonaje() {
		return this.personaje;
	}

	public void setPersonaje(Personaje personaje) {
		this.personaje = personaje;
	}

	@Column(name = "AGILIDAD", nullable = false)
	public int getAgilidad() {
		return this.agilidad;
	}

	public void setAgilidad(int agilidad) {
		this.agilidad = agilidad;
	}

	@Column(name = "CONSTITUCION", nullable = false)
	public int getConstitucion() {
		return this.constitucion;
	}

	public void setConstitucion(int constitucion) {
		this.constitucion = constitucion;
	}

	@Column(name = "DESTREZA", nullable = false)
	public int getDestreza() {
		return this.destreza;
	}

	public void setDestreza(int destreza) {
		this.destreza = destreza;
	}

	@Column(name = "FUERZA", nullable = false)
	public int getFuerza() {
		return this.fuerza;
	}

	public void setFuerza(int fuerza) {
		this.fuerza = fuerza;
	}

	@Column(name = "INTELIGENCIA", nullable = false)
	public int getInteligencia() {
		return this.inteligencia;
	}

	public void setInteligencia(int inteligencia) {
		this.inteligencia = inteligencia;
	}

	@Column(name = "PERCEPCION", nullable = false)
	public int getPercepcion() {
		return this.percepcion;
	}

	public void setPercepcion(int percepcion) {
		this.percepcion = percepcion;
	}

	@Column(name = "PODER", nullable = false)
	public int getPoder() {
		return this.poder;
	}

	public void setPoder(int poder) {
		this.poder = poder;
	}

	@Column(name = "VOLUNTAD", nullable = false)
	public int getVoluntad() {
		return this.voluntad;
	}

	public void setVoluntad(int voluntad) {
		this.voluntad = voluntad;
	}

	@Column(name = "AGILIDAD_TEMPORAL")
	public Integer getAgilidadTemporal() {
		return this.agilidadTemporal;
	}

	public void setAgilidadTemporal(Integer agilidadTemporal) {
		this.agilidadTemporal = agilidadTemporal;
	}

	@Column(name = "CONSTITUCION_TEMPORAL")
	public Integer getConstitucionTemporal() {
		return this.constitucionTemporal;
	}

	public void setConstitucionTemporal(Integer constitucionTemporal) {
		this.constitucionTemporal = constitucionTemporal;
	}

	@Column(name = "DESTREZA_TEMPORAL")
	public Integer getDestrezaTemporal() {
		return this.destrezaTemporal;
	}

	public void setDestrezaTemporal(Integer destrezaTemporal) {
		this.destrezaTemporal = destrezaTemporal;
	}

	@Column(name = "FUERZA_TEMPORAL")
	public Integer getFuerzaTemporal() {
		return this.fuerzaTemporal;
	}

	public void setFuerzaTemporal(Integer fuerzaTemporal) {
		this.fuerzaTemporal = fuerzaTemporal;
	}

	@Column(name = "INTELIGENCIA_TEMPORAL")
	public Integer getInteligenciaTemporal() {
		return this.inteligenciaTemporal;
	}

	public void setInteligenciaTemporal(Integer inteligenciaTemporal) {
		this.inteligenciaTemporal = inteligenciaTemporal;
	}

	@Column(name = "PERCEPCION_TEMPORAL")
	public Integer getPercepcionTemporal() {
		return this.percepcionTemporal;
	}

	public void setPercepcionTemporal(Integer percepcionTemporal) {
		this.percepcionTemporal = percepcionTemporal;
	}

	@Column(name = "PODER_TEMPORAL")
	public Integer getPoderTemporal() {
		return this.poderTemporal;
	}

	public void setPoderTemporal(Integer poderTemporal) {
		this.poderTemporal = poderTemporal;
	}

	@Column(name = "VOLUNTAD_TEMPORAL")
	public Integer getVoluntadTemporal() {
		return this.voluntadTemporal;
	}

	public void setVoluntadTemporal(Integer voluntadTemporal) {
		this.voluntadTemporal = voluntadTemporal;
	}

}
