package modelo;
// Generated 15 jun. 2021 21:58:49 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Desventaja generated by hbm2java
 */
@Entity
@Table(name = "desventaja", catalog = "anima_sheets_data")
public class Desventaja implements java.io.Serializable {

	private Integer idDesventaja;
	private String nombre;
	private String descripcion;
	private int beneficio;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public Desventaja() {
	}

	public Desventaja(String nombre, String descripcion, int beneficio) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.beneficio = beneficio;
	}

	public Desventaja(String nombre, String descripcion, int beneficio, Set<Personaje> personajes) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.beneficio = beneficio;
		this.personajes = personajes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_DESVENTAJA", unique = true, nullable = false)
	public Integer getIdDesventaja() {
		return this.idDesventaja;
	}

	public void setIdDesventaja(Integer idDesventaja) {
		this.idDesventaja = idDesventaja;
	}

	@Column(name = "NOMBRE", nullable = false, length = 65535)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "BENEFICIO", nullable = false)
	public int getBeneficio() {
		return this.beneficio;
	}

	public void setBeneficio(int beneficio) {
		this.beneficio = beneficio;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tabla_desventaja_personaje", catalog = "anima_sheets_data", joinColumns = {
			@JoinColumn(name = "ID_DESVENTAJA", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_PERSONAJE", nullable = false, updatable = false) })
	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

}
