package modelo;
// Generated 15 jun. 2021 23:20:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Idioma generated by hbm2java
 */
@Entity
@Table(name = "idioma", catalog = "anima_sheets_data")
public class Idioma implements java.io.Serializable {

	private int idIdioma;
	private String nombre;
	private Integer conHistoriaReq;
	private Integer conOcultismoReq;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public Idioma() {
	}

	public Idioma(int idIdioma, String nombre) {
		this.idIdioma = idIdioma;
		this.nombre = nombre;
	}

	public Idioma(int idIdioma, String nombre, Integer conHistoriaReq, Integer conOcultismoReq,
			Set<Personaje> personajes) {
		this.idIdioma = idIdioma;
		this.nombre = nombre;
		this.conHistoriaReq = conHistoriaReq;
		this.conOcultismoReq = conOcultismoReq;
		this.personajes = personajes;
	}

	@Id

	@Column(name = "ID_IDIOMA", unique = true, nullable = false)
	public int getIdIdioma() {
		return this.idIdioma;
	}

	public void setIdIdioma(int idIdioma) {
		this.idIdioma = idIdioma;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "CON_HISTORIA_REQ")
	public Integer getConHistoriaReq() {
		return this.conHistoriaReq;
	}

	public void setConHistoriaReq(Integer conHistoriaReq) {
		this.conHistoriaReq = conHistoriaReq;
	}

	@Column(name = "CON_OCULTISMO_REQ")
	public Integer getConOcultismoReq() {
		return this.conOcultismoReq;
	}

	public void setConOcultismoReq(Integer conOcultismoReq) {
		this.conOcultismoReq = conOcultismoReq;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tabla_idioma_personaje", catalog = "anima_sheets_data", joinColumns = {
			@JoinColumn(name = "ID_IDIOMA", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_PERSONAJE", nullable = false, updatable = false) })
	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

}
