package modelo;
// Generated 14 jun. 2021 19:59:45 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name = "jugador", catalog = "anima_sheets_data")
public class Jugador implements java.io.Serializable {

	private int idJugador;
	private String nombre;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public Jugador() {
	}

	public Jugador(int idJugador, String nombre) {
		this.idJugador = idJugador;
		this.nombre = nombre;
	}

	public Jugador(int idJugador, String nombre, Set<Personaje> personajes) {
		this.idJugador = idJugador;
		this.nombre = nombre;
		this.personajes = personajes;
	}

	@Id

	@Column(name = "ID_JUGADOR", unique = true, nullable = false)
	public int getIdJugador() {
		return this.idJugador;
	}

	public void setIdJugador(int idJugador) {
		this.idJugador = idJugador;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugador")
	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

}
