package modelo;
// Generated 13 jun. 2021 23:25:16 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Lv generated by hbm2java
 */
@Entity
@Table(name = "lv", catalog = "anima_sheets_data")
public class Lv implements java.io.Serializable {

	private int idPersonaje;
	private Personaje personaje;
	private int lv;
	private Integer lvGuerrero;
	private Integer lvGuerreroAcrobata;
	private Integer lvPaladin;
	private Integer lvPaladinOscuro;
	private Integer lvMaestroArmas;
	private Integer lvTecnicista;
	private Integer lvTao;
	private Integer lvExplorador;
	private Integer lvSombra;
	private Integer lvLadron;
	private Integer lvHechicero;
	private Integer lvWarlock;
	private Integer lvIlusionista;
	private Integer lvHechiceroMentalista;
	private Integer lvConjurador;
	private Integer lvGuerreroConjurador;
	private Integer lvMentalista;
	private Integer lvGuerreroMentalista;
	private Integer lvNovel;
	private Integer lv1Guerrero;
	private Integer lv1GuerreroAcrobata;
	private Integer lv1Paladin;
	private Integer lv1PaladinOscuro;
	private Integer lv1MaestroArmas;
	private Integer lv1Tecnicista;
	private Integer lv1Tao;
	private Integer lv1Explorador;
	private Integer lv1Sombra;
	private Integer lv1Ladron;
	private Integer lv1Hechicero;
	private Integer lv1Warlock;
	private Integer lv1Ilusionista;
	private Integer lv1HechiceroMentalista;
	private Integer lv1Conjurador;
	private Integer lv1GuerreroConjurador;
	private Integer lv1Mentalista;
	private Integer lv1GuerreroMentalista;
	private Integer lv1Novel;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public Lv() {
	}

	public Lv(Personaje personaje, int lv) {
		this.personaje = personaje;
		this.lv = lv;
	}

	public Lv(Personaje personaje, int lv, Integer lvGuerrero, Integer lvGuerreroAcrobata, Integer lvPaladin,
			Integer lvPaladinOscuro, Integer lvMaestroArmas, Integer lvTecnicista, Integer lvTao, Integer lvExplorador,
			Integer lvSombra, Integer lvLadron, Integer lvHechicero, Integer lvWarlock, Integer lvIlusionista,
			Integer lvHechiceroMentalista, Integer lvConjurador, Integer lvGuerreroConjurador, Integer lvMentalista,
			Integer lvGuerreroMentalista, Integer lvNovel, Integer lv1Guerrero, Integer lv1GuerreroAcrobata,
			Integer lv1Paladin, Integer lv1PaladinOscuro, Integer lv1MaestroArmas, Integer lv1Tecnicista,
			Integer lv1Tao, Integer lv1Explorador, Integer lv1Sombra, Integer lv1Ladron, Integer lv1Hechicero,
			Integer lv1Warlock, Integer lv1Ilusionista, Integer lv1HechiceroMentalista, Integer lv1Conjurador,
			Integer lv1GuerreroConjurador, Integer lv1Mentalista, Integer lv1GuerreroMentalista, Integer lv1Novel,
			Set<PdsCategoria> pdsCategorias) {
		this.personaje = personaje;
		this.lv = lv;
		this.lvGuerrero = lvGuerrero;
		this.lvGuerreroAcrobata = lvGuerreroAcrobata;
		this.lvPaladin = lvPaladin;
		this.lvPaladinOscuro = lvPaladinOscuro;
		this.lvMaestroArmas = lvMaestroArmas;
		this.lvTecnicista = lvTecnicista;
		this.lvTao = lvTao;
		this.lvExplorador = lvExplorador;
		this.lvSombra = lvSombra;
		this.lvLadron = lvLadron;
		this.lvHechicero = lvHechicero;
		this.lvWarlock = lvWarlock;
		this.lvIlusionista = lvIlusionista;
		this.lvHechiceroMentalista = lvHechiceroMentalista;
		this.lvConjurador = lvConjurador;
		this.lvGuerreroConjurador = lvGuerreroConjurador;
		this.lvMentalista = lvMentalista;
		this.lvGuerreroMentalista = lvGuerreroMentalista;
		this.lvNovel = lvNovel;
		this.lv1Guerrero = lv1Guerrero;
		this.lv1GuerreroAcrobata = lv1GuerreroAcrobata;
		this.lv1Paladin = lv1Paladin;
		this.lv1PaladinOscuro = lv1PaladinOscuro;
		this.lv1MaestroArmas = lv1MaestroArmas;
		this.lv1Tecnicista = lv1Tecnicista;
		this.lv1Tao = lv1Tao;
		this.lv1Explorador = lv1Explorador;
		this.lv1Sombra = lv1Sombra;
		this.lv1Ladron = lv1Ladron;
		this.lv1Hechicero = lv1Hechicero;
		this.lv1Warlock = lv1Warlock;
		this.lv1Ilusionista = lv1Ilusionista;
		this.lv1HechiceroMentalista = lv1HechiceroMentalista;
		this.lv1Conjurador = lv1Conjurador;
		this.lv1GuerreroConjurador = lv1GuerreroConjurador;
		this.lv1Mentalista = lv1Mentalista;
		this.lv1GuerreroMentalista = lv1GuerreroMentalista;
		this.lv1Novel = lv1Novel;
		this.pdsCategorias = pdsCategorias;
	}

	@GenericGenerator(name = "modelo.LvIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personaje"))
	@Id
	@GeneratedValue(generator = "modelo.LvIdGenerator")

	@Column(name = "ID_PERSONAJE", unique = true, nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personaje getPersonaje() {
		return this.personaje;
	}

	public void setPersonaje(Personaje personaje) {
		this.personaje = personaje;
	}

	@Column(name = "LV", nullable = false)
	public int getLv() {
		return this.lv;
	}

	public void setLv(int lv) {
		this.lv = lv;
	}

	@Column(name = "LV_GUERRERO")
	public Integer getLvGuerrero() {
		return this.lvGuerrero;
	}

	public void setLvGuerrero(Integer lvGuerrero) {
		this.lvGuerrero = lvGuerrero;
	}

	@Column(name = "LV_GUERRERO_ACROBATA")
	public Integer getLvGuerreroAcrobata() {
		return this.lvGuerreroAcrobata;
	}

	public void setLvGuerreroAcrobata(Integer lvGuerreroAcrobata) {
		this.lvGuerreroAcrobata = lvGuerreroAcrobata;
	}

	@Column(name = "LV_PALADIN")
	public Integer getLvPaladin() {
		return this.lvPaladin;
	}

	public void setLvPaladin(Integer lvPaladin) {
		this.lvPaladin = lvPaladin;
	}

	@Column(name = "LV_PALADIN_OSCURO")
	public Integer getLvPaladinOscuro() {
		return this.lvPaladinOscuro;
	}

	public void setLvPaladinOscuro(Integer lvPaladinOscuro) {
		this.lvPaladinOscuro = lvPaladinOscuro;
	}

	@Column(name = "LV_MAESTRO_ARMAS")
	public Integer getLvMaestroArmas() {
		return this.lvMaestroArmas;
	}

	public void setLvMaestroArmas(Integer lvMaestroArmas) {
		this.lvMaestroArmas = lvMaestroArmas;
	}

	@Column(name = "LV_TECNICISTA")
	public Integer getLvTecnicista() {
		return this.lvTecnicista;
	}

	public void setLvTecnicista(Integer lvTecnicista) {
		this.lvTecnicista = lvTecnicista;
	}

	@Column(name = "LV_TAO")
	public Integer getLvTao() {
		return this.lvTao;
	}

	public void setLvTao(Integer lvTao) {
		this.lvTao = lvTao;
	}

	@Column(name = "LV_EXPLORADOR")
	public Integer getLvExplorador() {
		return this.lvExplorador;
	}

	public void setLvExplorador(Integer lvExplorador) {
		this.lvExplorador = lvExplorador;
	}

	@Column(name = "LV_SOMBRA")
	public Integer getLvSombra() {
		return this.lvSombra;
	}

	public void setLvSombra(Integer lvSombra) {
		this.lvSombra = lvSombra;
	}

	@Column(name = "LV_LADRON")
	public Integer getLvLadron() {
		return this.lvLadron;
	}

	public void setLvLadron(Integer lvLadron) {
		this.lvLadron = lvLadron;
	}

	@Column(name = "LV_HECHICERO")
	public Integer getLvHechicero() {
		return this.lvHechicero;
	}

	public void setLvHechicero(Integer lvHechicero) {
		this.lvHechicero = lvHechicero;
	}

	@Column(name = "LV_WARLOCK")
	public Integer getLvWarlock() {
		return this.lvWarlock;
	}

	public void setLvWarlock(Integer lvWarlock) {
		this.lvWarlock = lvWarlock;
	}

	@Column(name = "LV_ILUSIONISTA")
	public Integer getLvIlusionista() {
		return this.lvIlusionista;
	}

	public void setLvIlusionista(Integer lvIlusionista) {
		this.lvIlusionista = lvIlusionista;
	}

	@Column(name = "LV_HECHICERO_MENTALISTA")
	public Integer getLvHechiceroMentalista() {
		return this.lvHechiceroMentalista;
	}

	public void setLvHechiceroMentalista(Integer lvHechiceroMentalista) {
		this.lvHechiceroMentalista = lvHechiceroMentalista;
	}

	@Column(name = "LV_CONJURADOR")
	public Integer getLvConjurador() {
		return this.lvConjurador;
	}

	public void setLvConjurador(Integer lvConjurador) {
		this.lvConjurador = lvConjurador;
	}

	@Column(name = "LV_GUERRERO_CONJURADOR")
	public Integer getLvGuerreroConjurador() {
		return this.lvGuerreroConjurador;
	}

	public void setLvGuerreroConjurador(Integer lvGuerreroConjurador) {
		this.lvGuerreroConjurador = lvGuerreroConjurador;
	}

	@Column(name = "LV_MENTALISTA")
	public Integer getLvMentalista() {
		return this.lvMentalista;
	}

	public void setLvMentalista(Integer lvMentalista) {
		this.lvMentalista = lvMentalista;
	}

	@Column(name = "LV_GUERRERO_MENTALISTA")
	public Integer getLvGuerreroMentalista() {
		return this.lvGuerreroMentalista;
	}

	public void setLvGuerreroMentalista(Integer lvGuerreroMentalista) {
		this.lvGuerreroMentalista = lvGuerreroMentalista;
	}

	@Column(name = "LV_NOVEL")
	public Integer getLvNovel() {
		return this.lvNovel;
	}

	public void setLvNovel(Integer lvNovel) {
		this.lvNovel = lvNovel;
	}

	@Column(name = "LV1_GUERRERO")
	public Integer getLv1Guerrero() {
		return this.lv1Guerrero;
	}

	public void setLv1Guerrero(Integer lv1Guerrero) {
		this.lv1Guerrero = lv1Guerrero;
	}

	@Column(name = "LV1_GUERRERO_ACROBATA")
	public Integer getLv1GuerreroAcrobata() {
		return this.lv1GuerreroAcrobata;
	}

	public void setLv1GuerreroAcrobata(Integer lv1GuerreroAcrobata) {
		this.lv1GuerreroAcrobata = lv1GuerreroAcrobata;
	}

	@Column(name = "LV1_PALADIN")
	public Integer getLv1Paladin() {
		return this.lv1Paladin;
	}

	public void setLv1Paladin(Integer lv1Paladin) {
		this.lv1Paladin = lv1Paladin;
	}

	@Column(name = "LV1_PALADIN_OSCURO")
	public Integer getLv1PaladinOscuro() {
		return this.lv1PaladinOscuro;
	}

	public void setLv1PaladinOscuro(Integer lv1PaladinOscuro) {
		this.lv1PaladinOscuro = lv1PaladinOscuro;
	}

	@Column(name = "LV1_MAESTRO_ARMAS")
	public Integer getLv1MaestroArmas() {
		return this.lv1MaestroArmas;
	}

	public void setLv1MaestroArmas(Integer lv1MaestroArmas) {
		this.lv1MaestroArmas = lv1MaestroArmas;
	}

	@Column(name = "LV1_TECNICISTA")
	public Integer getLv1Tecnicista() {
		return this.lv1Tecnicista;
	}

	public void setLv1Tecnicista(Integer lv1Tecnicista) {
		this.lv1Tecnicista = lv1Tecnicista;
	}

	@Column(name = "LV1_TAO")
	public Integer getLv1Tao() {
		return this.lv1Tao;
	}

	public void setLv1Tao(Integer lv1Tao) {
		this.lv1Tao = lv1Tao;
	}

	@Column(name = "LV1_EXPLORADOR")
	public Integer getLv1Explorador() {
		return this.lv1Explorador;
	}

	public void setLv1Explorador(Integer lv1Explorador) {
		this.lv1Explorador = lv1Explorador;
	}

	@Column(name = "LV1_SOMBRA")
	public Integer getLv1Sombra() {
		return this.lv1Sombra;
	}

	public void setLv1Sombra(Integer lv1Sombra) {
		this.lv1Sombra = lv1Sombra;
	}

	@Column(name = "LV1_LADRON")
	public Integer getLv1Ladron() {
		return this.lv1Ladron;
	}

	public void setLv1Ladron(Integer lv1Ladron) {
		this.lv1Ladron = lv1Ladron;
	}

	@Column(name = "LV1_HECHICERO")
	public Integer getLv1Hechicero() {
		return this.lv1Hechicero;
	}

	public void setLv1Hechicero(Integer lv1Hechicero) {
		this.lv1Hechicero = lv1Hechicero;
	}

	@Column(name = "LV1_WARLOCK")
	public Integer getLv1Warlock() {
		return this.lv1Warlock;
	}

	public void setLv1Warlock(Integer lv1Warlock) {
		this.lv1Warlock = lv1Warlock;
	}

	@Column(name = "LV1_ILUSIONISTA")
	public Integer getLv1Ilusionista() {
		return this.lv1Ilusionista;
	}

	public void setLv1Ilusionista(Integer lv1Ilusionista) {
		this.lv1Ilusionista = lv1Ilusionista;
	}

	@Column(name = "LV1_HECHICERO_MENTALISTA")
	public Integer getLv1HechiceroMentalista() {
		return this.lv1HechiceroMentalista;
	}

	public void setLv1HechiceroMentalista(Integer lv1HechiceroMentalista) {
		this.lv1HechiceroMentalista = lv1HechiceroMentalista;
	}

	@Column(name = "LV1_CONJURADOR")
	public Integer getLv1Conjurador() {
		return this.lv1Conjurador;
	}

	public void setLv1Conjurador(Integer lv1Conjurador) {
		this.lv1Conjurador = lv1Conjurador;
	}

	@Column(name = "LV1_GUERRERO_CONJURADOR")
	public Integer getLv1GuerreroConjurador() {
		return this.lv1GuerreroConjurador;
	}

	public void setLv1GuerreroConjurador(Integer lv1GuerreroConjurador) {
		this.lv1GuerreroConjurador = lv1GuerreroConjurador;
	}

	@Column(name = "LV1_MENTALISTA")
	public Integer getLv1Mentalista() {
		return this.lv1Mentalista;
	}

	public void setLv1Mentalista(Integer lv1Mentalista) {
		this.lv1Mentalista = lv1Mentalista;
	}

	@Column(name = "LV1_GUERRERO_MENTALISTA")
	public Integer getLv1GuerreroMentalista() {
		return this.lv1GuerreroMentalista;
	}

	public void setLv1GuerreroMentalista(Integer lv1GuerreroMentalista) {
		this.lv1GuerreroMentalista = lv1GuerreroMentalista;
	}

	@Column(name = "LV1_NOVEL")
	public Integer getLv1Novel() {
		return this.lv1Novel;
	}

	public void setLv1Novel(Integer lv1Novel) {
		this.lv1Novel = lv1Novel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lv")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
