package modelo;
// Generated 13 jun. 2021 23:25:16 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PdsCategoriaId generated by hbm2java
 */
@Embeddable
public class PdsCategoriaId implements java.io.Serializable {

	private int idCategoria;
	private int idPersonaje;
	private int pdsPrimariasComunes;
	private int pdsPrimariasKi;
	private int pdsPrimariasTablasComunes;
	private int pdsPrimariasMisticas;
	private int pdsPrimariasPsiquicas;
	private int pdsPrimariasPatronesPsiquicos;
	private int pdsSecundariasAtleticas;
	private int pdsSecundariasSociales;
	private int pdsSecundariasPerceptivas;
	private int pdsSecundariasIntelectuales;
	private int pdsSecundariasVigor;
	private int pdsSecundariasSubterfugio;
	private int pdsSecundariasCreativas;

	public PdsCategoriaId() {
	}

	public PdsCategoriaId(int idCategoria, int idPersonaje, int pdsPrimariasComunes, int pdsPrimariasKi,
			int pdsPrimariasTablasComunes, int pdsPrimariasMisticas, int pdsPrimariasPsiquicas,
			int pdsPrimariasPatronesPsiquicos, int pdsSecundariasAtleticas, int pdsSecundariasSociales,
			int pdsSecundariasPerceptivas, int pdsSecundariasIntelectuales, int pdsSecundariasVigor,
			int pdsSecundariasSubterfugio, int pdsSecundariasCreativas) {
		this.idCategoria = idCategoria;
		this.idPersonaje = idPersonaje;
		this.pdsPrimariasComunes = pdsPrimariasComunes;
		this.pdsPrimariasKi = pdsPrimariasKi;
		this.pdsPrimariasTablasComunes = pdsPrimariasTablasComunes;
		this.pdsPrimariasMisticas = pdsPrimariasMisticas;
		this.pdsPrimariasPsiquicas = pdsPrimariasPsiquicas;
		this.pdsPrimariasPatronesPsiquicos = pdsPrimariasPatronesPsiquicos;
		this.pdsSecundariasAtleticas = pdsSecundariasAtleticas;
		this.pdsSecundariasSociales = pdsSecundariasSociales;
		this.pdsSecundariasPerceptivas = pdsSecundariasPerceptivas;
		this.pdsSecundariasIntelectuales = pdsSecundariasIntelectuales;
		this.pdsSecundariasVigor = pdsSecundariasVigor;
		this.pdsSecundariasSubterfugio = pdsSecundariasSubterfugio;
		this.pdsSecundariasCreativas = pdsSecundariasCreativas;
	}

	@Column(name = "ID_CATEGORIA", nullable = false)
	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "ID_PERSONAJE", nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	@Column(name = "PDS_PRIMARIAS_COMUNES", nullable = false)
	public int getPdsPrimariasComunes() {
		return this.pdsPrimariasComunes;
	}

	public void setPdsPrimariasComunes(int pdsPrimariasComunes) {
		this.pdsPrimariasComunes = pdsPrimariasComunes;
	}

	@Column(name = "PDS_PRIMARIAS_KI", nullable = false)
	public int getPdsPrimariasKi() {
		return this.pdsPrimariasKi;
	}

	public void setPdsPrimariasKi(int pdsPrimariasKi) {
		this.pdsPrimariasKi = pdsPrimariasKi;
	}

	@Column(name = "PDS_PRIMARIAS_TABLAS_COMUNES", nullable = false)
	public int getPdsPrimariasTablasComunes() {
		return this.pdsPrimariasTablasComunes;
	}

	public void setPdsPrimariasTablasComunes(int pdsPrimariasTablasComunes) {
		this.pdsPrimariasTablasComunes = pdsPrimariasTablasComunes;
	}

	@Column(name = "PDS_PRIMARIAS_MISTICAS", nullable = false)
	public int getPdsPrimariasMisticas() {
		return this.pdsPrimariasMisticas;
	}

	public void setPdsPrimariasMisticas(int pdsPrimariasMisticas) {
		this.pdsPrimariasMisticas = pdsPrimariasMisticas;
	}

	@Column(name = "PDS_PRIMARIAS_PSIQUICAS", nullable = false)
	public int getPdsPrimariasPsiquicas() {
		return this.pdsPrimariasPsiquicas;
	}

	public void setPdsPrimariasPsiquicas(int pdsPrimariasPsiquicas) {
		this.pdsPrimariasPsiquicas = pdsPrimariasPsiquicas;
	}

	@Column(name = "PDS_PRIMARIAS_PATRONES_PSIQUICOS", nullable = false)
	public int getPdsPrimariasPatronesPsiquicos() {
		return this.pdsPrimariasPatronesPsiquicos;
	}

	public void setPdsPrimariasPatronesPsiquicos(int pdsPrimariasPatronesPsiquicos) {
		this.pdsPrimariasPatronesPsiquicos = pdsPrimariasPatronesPsiquicos;
	}

	@Column(name = "PDS_SECUNDARIAS_ATLETICAS", nullable = false)
	public int getPdsSecundariasAtleticas() {
		return this.pdsSecundariasAtleticas;
	}

	public void setPdsSecundariasAtleticas(int pdsSecundariasAtleticas) {
		this.pdsSecundariasAtleticas = pdsSecundariasAtleticas;
	}

	@Column(name = "PDS_SECUNDARIAS_SOCIALES", nullable = false)
	public int getPdsSecundariasSociales() {
		return this.pdsSecundariasSociales;
	}

	public void setPdsSecundariasSociales(int pdsSecundariasSociales) {
		this.pdsSecundariasSociales = pdsSecundariasSociales;
	}

	@Column(name = "PDS_SECUNDARIAS_PERCEPTIVAS", nullable = false)
	public int getPdsSecundariasPerceptivas() {
		return this.pdsSecundariasPerceptivas;
	}

	public void setPdsSecundariasPerceptivas(int pdsSecundariasPerceptivas) {
		this.pdsSecundariasPerceptivas = pdsSecundariasPerceptivas;
	}

	@Column(name = "PDS_SECUNDARIAS_INTELECTUALES", nullable = false)
	public int getPdsSecundariasIntelectuales() {
		return this.pdsSecundariasIntelectuales;
	}

	public void setPdsSecundariasIntelectuales(int pdsSecundariasIntelectuales) {
		this.pdsSecundariasIntelectuales = pdsSecundariasIntelectuales;
	}

	@Column(name = "PDS_SECUNDARIAS_VIGOR", nullable = false)
	public int getPdsSecundariasVigor() {
		return this.pdsSecundariasVigor;
	}

	public void setPdsSecundariasVigor(int pdsSecundariasVigor) {
		this.pdsSecundariasVigor = pdsSecundariasVigor;
	}

	@Column(name = "PDS_SECUNDARIAS_SUBTERFUGIO", nullable = false)
	public int getPdsSecundariasSubterfugio() {
		return this.pdsSecundariasSubterfugio;
	}

	public void setPdsSecundariasSubterfugio(int pdsSecundariasSubterfugio) {
		this.pdsSecundariasSubterfugio = pdsSecundariasSubterfugio;
	}

	@Column(name = "PDS_SECUNDARIAS_CREATIVAS", nullable = false)
	public int getPdsSecundariasCreativas() {
		return this.pdsSecundariasCreativas;
	}

	public void setPdsSecundariasCreativas(int pdsSecundariasCreativas) {
		this.pdsSecundariasCreativas = pdsSecundariasCreativas;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PdsCategoriaId))
			return false;
		PdsCategoriaId castOther = (PdsCategoriaId) other;

		return (this.getIdCategoria() == castOther.getIdCategoria())
				&& (this.getIdPersonaje() == castOther.getIdPersonaje())
				&& (this.getPdsPrimariasComunes() == castOther.getPdsPrimariasComunes())
				&& (this.getPdsPrimariasKi() == castOther.getPdsPrimariasKi())
				&& (this.getPdsPrimariasTablasComunes() == castOther.getPdsPrimariasTablasComunes())
				&& (this.getPdsPrimariasMisticas() == castOther.getPdsPrimariasMisticas())
				&& (this.getPdsPrimariasPsiquicas() == castOther.getPdsPrimariasPsiquicas())
				&& (this.getPdsPrimariasPatronesPsiquicos() == castOther.getPdsPrimariasPatronesPsiquicos())
				&& (this.getPdsSecundariasAtleticas() == castOther.getPdsSecundariasAtleticas())
				&& (this.getPdsSecundariasSociales() == castOther.getPdsSecundariasSociales())
				&& (this.getPdsSecundariasPerceptivas() == castOther.getPdsSecundariasPerceptivas())
				&& (this.getPdsSecundariasIntelectuales() == castOther.getPdsSecundariasIntelectuales())
				&& (this.getPdsSecundariasVigor() == castOther.getPdsSecundariasVigor())
				&& (this.getPdsSecundariasSubterfugio() == castOther.getPdsSecundariasSubterfugio())
				&& (this.getPdsSecundariasCreativas() == castOther.getPdsSecundariasCreativas());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCategoria();
		result = 37 * result + this.getIdPersonaje();
		result = 37 * result + this.getPdsPrimariasComunes();
		result = 37 * result + this.getPdsPrimariasKi();
		result = 37 * result + this.getPdsPrimariasTablasComunes();
		result = 37 * result + this.getPdsPrimariasMisticas();
		result = 37 * result + this.getPdsPrimariasPsiquicas();
		result = 37 * result + this.getPdsPrimariasPatronesPsiquicos();
		result = 37 * result + this.getPdsSecundariasAtleticas();
		result = 37 * result + this.getPdsSecundariasSociales();
		result = 37 * result + this.getPdsSecundariasPerceptivas();
		result = 37 * result + this.getPdsSecundariasIntelectuales();
		result = 37 * result + this.getPdsSecundariasVigor();
		result = 37 * result + this.getPdsSecundariasSubterfugio();
		result = 37 * result + this.getPdsSecundariasCreativas();
		return result;
	}

}
