package modelo;
// Generated 15 jun. 2021 0:01:59 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PdsPrimariasPsiquicas generated by hbm2java
 */
@Entity
@Table(name = "pds_primarias_psiquicas", catalog = "anima_sheets_data")
public class PdsPrimariasPsiquicas implements java.io.Serializable {

	private int pdsPrimariasPsiquicas;
	private Integer pdsCv;
	private Integer pdsProyeccionPsiquica;
	private Integer pdsEspCv;
	private Integer pdsEspProyeccionPsiquica;
	private Integer pdsTablaPsiquico;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public PdsPrimariasPsiquicas() {
	}

	public PdsPrimariasPsiquicas(int pdsPrimariasPsiquicas) {
		this.pdsPrimariasPsiquicas = pdsPrimariasPsiquicas;
	}

	public PdsPrimariasPsiquicas(int pdsPrimariasPsiquicas, Integer pdsCv, Integer pdsProyeccionPsiquica,
			Integer pdsEspCv, Integer pdsEspProyeccionPsiquica, Integer pdsTablaPsiquico,
			Set<PdsCategoria> pdsCategorias) {
		this.pdsPrimariasPsiquicas = pdsPrimariasPsiquicas;
		this.pdsCv = pdsCv;
		this.pdsProyeccionPsiquica = pdsProyeccionPsiquica;
		this.pdsEspCv = pdsEspCv;
		this.pdsEspProyeccionPsiquica = pdsEspProyeccionPsiquica;
		this.pdsTablaPsiquico = pdsTablaPsiquico;
		this.pdsCategorias = pdsCategorias;
	}

	@Id

	@Column(name = "PDS_PRIMARIAS_PSIQUICAS", unique = true, nullable = false)
	public int getPdsPrimariasPsiquicas() {
		return this.pdsPrimariasPsiquicas;
	}

	public void setPdsPrimariasPsiquicas(int pdsPrimariasPsiquicas) {
		this.pdsPrimariasPsiquicas = pdsPrimariasPsiquicas;
	}

	@Column(name = "PDS_CV")
	public Integer getPdsCv() {
		return this.pdsCv;
	}

	public void setPdsCv(Integer pdsCv) {
		this.pdsCv = pdsCv;
	}

	@Column(name = "PDS_PROYECCION_PSIQUICA")
	public Integer getPdsProyeccionPsiquica() {
		return this.pdsProyeccionPsiquica;
	}

	public void setPdsProyeccionPsiquica(Integer pdsProyeccionPsiquica) {
		this.pdsProyeccionPsiquica = pdsProyeccionPsiquica;
	}

	@Column(name = "PDS_ESP_CV")
	public Integer getPdsEspCv() {
		return this.pdsEspCv;
	}

	public void setPdsEspCv(Integer pdsEspCv) {
		this.pdsEspCv = pdsEspCv;
	}

	@Column(name = "PDS_ESP_PROYECCION_PSIQUICA")
	public Integer getPdsEspProyeccionPsiquica() {
		return this.pdsEspProyeccionPsiquica;
	}

	public void setPdsEspProyeccionPsiquica(Integer pdsEspProyeccionPsiquica) {
		this.pdsEspProyeccionPsiquica = pdsEspProyeccionPsiquica;
	}

	@Column(name = "PDS_TABLA_PSIQUICO")
	public Integer getPdsTablaPsiquico() {
		return this.pdsTablaPsiquico;
	}

	public void setPdsTablaPsiquico(Integer pdsTablaPsiquico) {
		this.pdsTablaPsiquico = pdsTablaPsiquico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdsPrimariasPsiquicas")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
