package modelo;
// Generated 15 jun. 2021 23:20:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PdsPrimariasPatronesPsiquicos generated by hbm2java
 */
@Entity
@Table(name = "pds_primarias_patrones_psiquicos", catalog = "anima_sheets_data")
public class PdsPrimariasPatronesPsiquicos implements java.io.Serializable {

	private int pdsPrimariasPatronesPsiquicos;
	private Integer pdsTablaPatronesMentales1;
	private Integer pdsTablaPatronesMentales2;
	private Integer pdsTablaPatronesMentales3;
	private Integer pdsTablaPatronesMentales4;
	private Integer pdsTablaPatronesMentales5;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public PdsPrimariasPatronesPsiquicos() {
	}

	public PdsPrimariasPatronesPsiquicos(int pdsPrimariasPatronesPsiquicos) {
		this.pdsPrimariasPatronesPsiquicos = pdsPrimariasPatronesPsiquicos;
	}

	public PdsPrimariasPatronesPsiquicos(int pdsPrimariasPatronesPsiquicos, Integer pdsTablaPatronesMentales1,
			Integer pdsTablaPatronesMentales2, Integer pdsTablaPatronesMentales3, Integer pdsTablaPatronesMentales4,
			Integer pdsTablaPatronesMentales5, Set<PdsCategoria> pdsCategorias) {
		this.pdsPrimariasPatronesPsiquicos = pdsPrimariasPatronesPsiquicos;
		this.pdsTablaPatronesMentales1 = pdsTablaPatronesMentales1;
		this.pdsTablaPatronesMentales2 = pdsTablaPatronesMentales2;
		this.pdsTablaPatronesMentales3 = pdsTablaPatronesMentales3;
		this.pdsTablaPatronesMentales4 = pdsTablaPatronesMentales4;
		this.pdsTablaPatronesMentales5 = pdsTablaPatronesMentales5;
		this.pdsCategorias = pdsCategorias;
	}

	@Id

	@Column(name = "PDS_PRIMARIAS_PATRONES_PSIQUICOS", unique = true, nullable = false)
	public int getPdsPrimariasPatronesPsiquicos() {
		return this.pdsPrimariasPatronesPsiquicos;
	}

	public void setPdsPrimariasPatronesPsiquicos(int pdsPrimariasPatronesPsiquicos) {
		this.pdsPrimariasPatronesPsiquicos = pdsPrimariasPatronesPsiquicos;
	}

	@Column(name = "PDS_TABLA_PATRONES_MENTALES1")
	public Integer getPdsTablaPatronesMentales1() {
		return this.pdsTablaPatronesMentales1;
	}

	public void setPdsTablaPatronesMentales1(Integer pdsTablaPatronesMentales1) {
		this.pdsTablaPatronesMentales1 = pdsTablaPatronesMentales1;
	}

	@Column(name = "PDS_TABLA_PATRONES_MENTALES2")
	public Integer getPdsTablaPatronesMentales2() {
		return this.pdsTablaPatronesMentales2;
	}

	public void setPdsTablaPatronesMentales2(Integer pdsTablaPatronesMentales2) {
		this.pdsTablaPatronesMentales2 = pdsTablaPatronesMentales2;
	}

	@Column(name = "PDS_TABLA_PATRONES_MENTALES3")
	public Integer getPdsTablaPatronesMentales3() {
		return this.pdsTablaPatronesMentales3;
	}

	public void setPdsTablaPatronesMentales3(Integer pdsTablaPatronesMentales3) {
		this.pdsTablaPatronesMentales3 = pdsTablaPatronesMentales3;
	}

	@Column(name = "PDS_TABLA_PATRONES_MENTALES4")
	public Integer getPdsTablaPatronesMentales4() {
		return this.pdsTablaPatronesMentales4;
	}

	public void setPdsTablaPatronesMentales4(Integer pdsTablaPatronesMentales4) {
		this.pdsTablaPatronesMentales4 = pdsTablaPatronesMentales4;
	}

	@Column(name = "PDS_TABLA_PATRONES_MENTALES5")
	public Integer getPdsTablaPatronesMentales5() {
		return this.pdsTablaPatronesMentales5;
	}

	public void setPdsTablaPatronesMentales5(Integer pdsTablaPatronesMentales5) {
		this.pdsTablaPatronesMentales5 = pdsTablaPatronesMentales5;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdsPrimariasPatronesPsiquicos")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
