package modelo;
// Generated 15 jun. 2021 0:01:59 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PdsPrimariasComunes generated by hbm2java
 */
@Entity
@Table(name = "pds_primarias_comunes", catalog = "anima_sheets_data")
public class PdsPrimariasComunes implements java.io.Serializable {

	private int pdsPrimariasComunes;
	private Integer pdsHa;
	private Integer pdsHp;
	private Integer pdsHe;
	private Integer pdsLlevarArmadura;
	private Integer pdsEspHa;
	private Integer pdsEspHp;
	private Integer pdsEspHe;
	private Integer pdsEspLlevarArmadura;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public PdsPrimariasComunes() {
	}

	public PdsPrimariasComunes(int pdsPrimariasComunes) {
		this.pdsPrimariasComunes = pdsPrimariasComunes;
	}

	public PdsPrimariasComunes(int pdsPrimariasComunes, Integer pdsHa, Integer pdsHp, Integer pdsHe,
			Integer pdsLlevarArmadura, Integer pdsEspHa, Integer pdsEspHp, Integer pdsEspHe,
			Integer pdsEspLlevarArmadura, Set<PdsCategoria> pdsCategorias) {
		this.pdsPrimariasComunes = pdsPrimariasComunes;
		this.pdsHa = pdsHa;
		this.pdsHp = pdsHp;
		this.pdsHe = pdsHe;
		this.pdsLlevarArmadura = pdsLlevarArmadura;
		this.pdsEspHa = pdsEspHa;
		this.pdsEspHp = pdsEspHp;
		this.pdsEspHe = pdsEspHe;
		this.pdsEspLlevarArmadura = pdsEspLlevarArmadura;
		this.pdsCategorias = pdsCategorias;
	}

	@Id

	@Column(name = "PDS_PRIMARIAS_COMUNES", unique = true, nullable = false)
	public int getPdsPrimariasComunes() {
		return this.pdsPrimariasComunes;
	}

	public void setPdsPrimariasComunes(int pdsPrimariasComunes) {
		this.pdsPrimariasComunes = pdsPrimariasComunes;
	}

	@Column(name = "PDS_HA")
	public Integer getPdsHa() {
		return this.pdsHa;
	}

	public void setPdsHa(Integer pdsHa) {
		this.pdsHa = pdsHa;
	}

	@Column(name = "PDS_HP")
	public Integer getPdsHp() {
		return this.pdsHp;
	}

	public void setPdsHp(Integer pdsHp) {
		this.pdsHp = pdsHp;
	}

	@Column(name = "PDS_HE")
	public Integer getPdsHe() {
		return this.pdsHe;
	}

	public void setPdsHe(Integer pdsHe) {
		this.pdsHe = pdsHe;
	}

	@Column(name = "PDS_LLEVAR_ARMADURA")
	public Integer getPdsLlevarArmadura() {
		return this.pdsLlevarArmadura;
	}

	public void setPdsLlevarArmadura(Integer pdsLlevarArmadura) {
		this.pdsLlevarArmadura = pdsLlevarArmadura;
	}

	@Column(name = "PDS_ESP_HA")
	public Integer getPdsEspHa() {
		return this.pdsEspHa;
	}

	public void setPdsEspHa(Integer pdsEspHa) {
		this.pdsEspHa = pdsEspHa;
	}

	@Column(name = "PDS_ESP_HP")
	public Integer getPdsEspHp() {
		return this.pdsEspHp;
	}

	public void setPdsEspHp(Integer pdsEspHp) {
		this.pdsEspHp = pdsEspHp;
	}

	@Column(name = "PDS_ESP_HE")
	public Integer getPdsEspHe() {
		return this.pdsEspHe;
	}

	public void setPdsEspHe(Integer pdsEspHe) {
		this.pdsEspHe = pdsEspHe;
	}

	@Column(name = "PDS_ESP_LLEVAR_ARMADURA")
	public Integer getPdsEspLlevarArmadura() {
		return this.pdsEspLlevarArmadura;
	}

	public void setPdsEspLlevarArmadura(Integer pdsEspLlevarArmadura) {
		this.pdsEspLlevarArmadura = pdsEspLlevarArmadura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdsPrimariasComunes")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
