package modelo;
// Generated 16 jun. 2021 23:54:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PdsPrimariasPsiquicas generated by hbm2java
 */
@Entity
@Table(name = "pds_primarias_psiquicas", catalog = "anima_sheets_data")
public class PdsPrimariasPsiquicas implements java.io.Serializable {

	private int idPersonaje;
	private Personaje personaje;
	private Integer pdsCv;
	private Integer pdsProyeccionPsiquica;
	private Integer pdsEspCv;
	private Integer pdsEspProyeccionPsiquica;
	private Integer pdsTablaPsiquico;

	public PdsPrimariasPsiquicas() {
	}

	public PdsPrimariasPsiquicas(Personaje personaje) {
		this.personaje = personaje;
	}

	public PdsPrimariasPsiquicas(Personaje personaje, Integer pdsCv, Integer pdsProyeccionPsiquica, Integer pdsEspCv,
			Integer pdsEspProyeccionPsiquica, Integer pdsTablaPsiquico) {
		this.personaje = personaje;
		this.pdsCv = pdsCv;
		this.pdsProyeccionPsiquica = pdsProyeccionPsiquica;
		this.pdsEspCv = pdsEspCv;
		this.pdsEspProyeccionPsiquica = pdsEspProyeccionPsiquica;
		this.pdsTablaPsiquico = pdsTablaPsiquico;
	}

	@GenericGenerator(name = "modelo.PdsPrimariasPsiquicasIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personaje"))
	@Id
	@GeneratedValue(generator = "modelo.PdsPrimariasPsiquicasIdGenerator")

	@Column(name = "ID_PERSONAJE", unique = true, nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personaje getPersonaje() {
		return this.personaje;
	}

	public void setPersonaje(Personaje personaje) {
		this.personaje = personaje;
	}

	@Column(name = "PDS_CV")
	public Integer getPdsCv() {
		return this.pdsCv;
	}

	public void setPdsCv(Integer pdsCv) {
		this.pdsCv = pdsCv;
	}

	@Column(name = "PDS_PROYECCION_PSIQUICA")
	public Integer getPdsProyeccionPsiquica() {
		return this.pdsProyeccionPsiquica;
	}

	public void setPdsProyeccionPsiquica(Integer pdsProyeccionPsiquica) {
		this.pdsProyeccionPsiquica = pdsProyeccionPsiquica;
	}

	@Column(name = "PDS_ESP_CV")
	public Integer getPdsEspCv() {
		return this.pdsEspCv;
	}

	public void setPdsEspCv(Integer pdsEspCv) {
		this.pdsEspCv = pdsEspCv;
	}

	@Column(name = "PDS_ESP_PROYECCION_PSIQUICA")
	public Integer getPdsEspProyeccionPsiquica() {
		return this.pdsEspProyeccionPsiquica;
	}

	public void setPdsEspProyeccionPsiquica(Integer pdsEspProyeccionPsiquica) {
		this.pdsEspProyeccionPsiquica = pdsEspProyeccionPsiquica;
	}

	@Column(name = "PDS_TABLA_PSIQUICO")
	public Integer getPdsTablaPsiquico() {
		return this.pdsTablaPsiquico;
	}

	public void setPdsTablaPsiquico(Integer pdsTablaPsiquico) {
		this.pdsTablaPsiquico = pdsTablaPsiquico;
	}

}
