package modelo;
// Generated 15 jun. 2021 23:20:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PdsPrimariasKi generated by hbm2java
 */
@Entity
@Table(name = "pds_primarias_ki", catalog = "anima_sheets_data")
public class PdsPrimariasKi implements java.io.Serializable {

	private int pdsPrimariasKi;
	private Integer pdsKiAgi;
	private Integer pdsKiCon;
	private Integer pdsKiDes;
	private Integer pdsKiFue;
	private Integer pdsKiPod;
	private Integer pdsKiVol;
	private Integer pdsAcuKiAgi;
	private Integer pdsAcuKiCon;
	private Integer pdsAcuKiDes;
	private Integer pdsAcuKiFue;
	private Integer pdsAcuKiPod;
	private Integer pdsAcuKiVol;
	private Integer pdsEspKiAgi;
	private Integer pdsEspKiCon;
	private Integer pdsEspKiDes;
	private Integer pdsEspKiFue;
	private Integer pdsEspKiPod;
	private Integer pdsEspKiVol;
	private Integer pdsEspAcuKiAgi;
	private Integer pdsEspAcuKiCon;
	private Integer pdsEspAcuKiDes;
	private Integer pdsEspAcuKiFue;
	private Integer pdsEspAcuKiPod;
	private Integer pdsEspAcuKiVol;
	private Integer pdsConocimientoMarcial;
	private Integer pdsEspConocimientoMarcial;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public PdsPrimariasKi() {
	}

	public PdsPrimariasKi(int pdsPrimariasKi) {
		this.pdsPrimariasKi = pdsPrimariasKi;
	}

	public PdsPrimariasKi(int pdsPrimariasKi, Integer pdsKiAgi, Integer pdsKiCon, Integer pdsKiDes, Integer pdsKiFue,
			Integer pdsKiPod, Integer pdsKiVol, Integer pdsAcuKiAgi, Integer pdsAcuKiCon, Integer pdsAcuKiDes,
			Integer pdsAcuKiFue, Integer pdsAcuKiPod, Integer pdsAcuKiVol, Integer pdsEspKiAgi, Integer pdsEspKiCon,
			Integer pdsEspKiDes, Integer pdsEspKiFue, Integer pdsEspKiPod, Integer pdsEspKiVol, Integer pdsEspAcuKiAgi,
			Integer pdsEspAcuKiCon, Integer pdsEspAcuKiDes, Integer pdsEspAcuKiFue, Integer pdsEspAcuKiPod,
			Integer pdsEspAcuKiVol, Integer pdsConocimientoMarcial, Integer pdsEspConocimientoMarcial,
			Set<PdsCategoria> pdsCategorias) {
		this.pdsPrimariasKi = pdsPrimariasKi;
		this.pdsKiAgi = pdsKiAgi;
		this.pdsKiCon = pdsKiCon;
		this.pdsKiDes = pdsKiDes;
		this.pdsKiFue = pdsKiFue;
		this.pdsKiPod = pdsKiPod;
		this.pdsKiVol = pdsKiVol;
		this.pdsAcuKiAgi = pdsAcuKiAgi;
		this.pdsAcuKiCon = pdsAcuKiCon;
		this.pdsAcuKiDes = pdsAcuKiDes;
		this.pdsAcuKiFue = pdsAcuKiFue;
		this.pdsAcuKiPod = pdsAcuKiPod;
		this.pdsAcuKiVol = pdsAcuKiVol;
		this.pdsEspKiAgi = pdsEspKiAgi;
		this.pdsEspKiCon = pdsEspKiCon;
		this.pdsEspKiDes = pdsEspKiDes;
		this.pdsEspKiFue = pdsEspKiFue;
		this.pdsEspKiPod = pdsEspKiPod;
		this.pdsEspKiVol = pdsEspKiVol;
		this.pdsEspAcuKiAgi = pdsEspAcuKiAgi;
		this.pdsEspAcuKiCon = pdsEspAcuKiCon;
		this.pdsEspAcuKiDes = pdsEspAcuKiDes;
		this.pdsEspAcuKiFue = pdsEspAcuKiFue;
		this.pdsEspAcuKiPod = pdsEspAcuKiPod;
		this.pdsEspAcuKiVol = pdsEspAcuKiVol;
		this.pdsConocimientoMarcial = pdsConocimientoMarcial;
		this.pdsEspConocimientoMarcial = pdsEspConocimientoMarcial;
		this.pdsCategorias = pdsCategorias;
	}

	@Id

	@Column(name = "PDS_PRIMARIAS_KI", unique = true, nullable = false)
	public int getPdsPrimariasKi() {
		return this.pdsPrimariasKi;
	}

	public void setPdsPrimariasKi(int pdsPrimariasKi) {
		this.pdsPrimariasKi = pdsPrimariasKi;
	}

	@Column(name = "PDS_KI_AGI")
	public Integer getPdsKiAgi() {
		return this.pdsKiAgi;
	}

	public void setPdsKiAgi(Integer pdsKiAgi) {
		this.pdsKiAgi = pdsKiAgi;
	}

	@Column(name = "PDS_KI_CON")
	public Integer getPdsKiCon() {
		return this.pdsKiCon;
	}

	public void setPdsKiCon(Integer pdsKiCon) {
		this.pdsKiCon = pdsKiCon;
	}

	@Column(name = "PDS_KI_DES")
	public Integer getPdsKiDes() {
		return this.pdsKiDes;
	}

	public void setPdsKiDes(Integer pdsKiDes) {
		this.pdsKiDes = pdsKiDes;
	}

	@Column(name = "PDS_KI_FUE")
	public Integer getPdsKiFue() {
		return this.pdsKiFue;
	}

	public void setPdsKiFue(Integer pdsKiFue) {
		this.pdsKiFue = pdsKiFue;
	}

	@Column(name = "PDS_KI_POD")
	public Integer getPdsKiPod() {
		return this.pdsKiPod;
	}

	public void setPdsKiPod(Integer pdsKiPod) {
		this.pdsKiPod = pdsKiPod;
	}

	@Column(name = "PDS_KI_VOL")
	public Integer getPdsKiVol() {
		return this.pdsKiVol;
	}

	public void setPdsKiVol(Integer pdsKiVol) {
		this.pdsKiVol = pdsKiVol;
	}

	@Column(name = "PDS_ACU_KI_AGI")
	public Integer getPdsAcuKiAgi() {
		return this.pdsAcuKiAgi;
	}

	public void setPdsAcuKiAgi(Integer pdsAcuKiAgi) {
		this.pdsAcuKiAgi = pdsAcuKiAgi;
	}

	@Column(name = "PDS_ACU_KI_CON")
	public Integer getPdsAcuKiCon() {
		return this.pdsAcuKiCon;
	}

	public void setPdsAcuKiCon(Integer pdsAcuKiCon) {
		this.pdsAcuKiCon = pdsAcuKiCon;
	}

	@Column(name = "PDS_ACU_KI_DES")
	public Integer getPdsAcuKiDes() {
		return this.pdsAcuKiDes;
	}

	public void setPdsAcuKiDes(Integer pdsAcuKiDes) {
		this.pdsAcuKiDes = pdsAcuKiDes;
	}

	@Column(name = "PDS_ACU_KI_FUE")
	public Integer getPdsAcuKiFue() {
		return this.pdsAcuKiFue;
	}

	public void setPdsAcuKiFue(Integer pdsAcuKiFue) {
		this.pdsAcuKiFue = pdsAcuKiFue;
	}

	@Column(name = "PDS_ACU_KI_POD")
	public Integer getPdsAcuKiPod() {
		return this.pdsAcuKiPod;
	}

	public void setPdsAcuKiPod(Integer pdsAcuKiPod) {
		this.pdsAcuKiPod = pdsAcuKiPod;
	}

	@Column(name = "PDS_ACU_KI_VOL")
	public Integer getPdsAcuKiVol() {
		return this.pdsAcuKiVol;
	}

	public void setPdsAcuKiVol(Integer pdsAcuKiVol) {
		this.pdsAcuKiVol = pdsAcuKiVol;
	}

	@Column(name = "PDS_ESP_KI_AGI")
	public Integer getPdsEspKiAgi() {
		return this.pdsEspKiAgi;
	}

	public void setPdsEspKiAgi(Integer pdsEspKiAgi) {
		this.pdsEspKiAgi = pdsEspKiAgi;
	}

	@Column(name = "PDS_ESP_KI_CON")
	public Integer getPdsEspKiCon() {
		return this.pdsEspKiCon;
	}

	public void setPdsEspKiCon(Integer pdsEspKiCon) {
		this.pdsEspKiCon = pdsEspKiCon;
	}

	@Column(name = "PDS_ESP_KI_DES")
	public Integer getPdsEspKiDes() {
		return this.pdsEspKiDes;
	}

	public void setPdsEspKiDes(Integer pdsEspKiDes) {
		this.pdsEspKiDes = pdsEspKiDes;
	}

	@Column(name = "PDS_ESP_KI_FUE")
	public Integer getPdsEspKiFue() {
		return this.pdsEspKiFue;
	}

	public void setPdsEspKiFue(Integer pdsEspKiFue) {
		this.pdsEspKiFue = pdsEspKiFue;
	}

	@Column(name = "PDS_ESP_KI_POD")
	public Integer getPdsEspKiPod() {
		return this.pdsEspKiPod;
	}

	public void setPdsEspKiPod(Integer pdsEspKiPod) {
		this.pdsEspKiPod = pdsEspKiPod;
	}

	@Column(name = "PDS_ESP_KI_VOL")
	public Integer getPdsEspKiVol() {
		return this.pdsEspKiVol;
	}

	public void setPdsEspKiVol(Integer pdsEspKiVol) {
		this.pdsEspKiVol = pdsEspKiVol;
	}

	@Column(name = "PDS_ESP_ACU_KI_AGI")
	public Integer getPdsEspAcuKiAgi() {
		return this.pdsEspAcuKiAgi;
	}

	public void setPdsEspAcuKiAgi(Integer pdsEspAcuKiAgi) {
		this.pdsEspAcuKiAgi = pdsEspAcuKiAgi;
	}

	@Column(name = "PDS_ESP_ACU_KI_CON")
	public Integer getPdsEspAcuKiCon() {
		return this.pdsEspAcuKiCon;
	}

	public void setPdsEspAcuKiCon(Integer pdsEspAcuKiCon) {
		this.pdsEspAcuKiCon = pdsEspAcuKiCon;
	}

	@Column(name = "PDS_ESP_ACU_KI_DES")
	public Integer getPdsEspAcuKiDes() {
		return this.pdsEspAcuKiDes;
	}

	public void setPdsEspAcuKiDes(Integer pdsEspAcuKiDes) {
		this.pdsEspAcuKiDes = pdsEspAcuKiDes;
	}

	@Column(name = "PDS_ESP_ACU_KI_FUE")
	public Integer getPdsEspAcuKiFue() {
		return this.pdsEspAcuKiFue;
	}

	public void setPdsEspAcuKiFue(Integer pdsEspAcuKiFue) {
		this.pdsEspAcuKiFue = pdsEspAcuKiFue;
	}

	@Column(name = "PDS_ESP_ACU_KI_POD")
	public Integer getPdsEspAcuKiPod() {
		return this.pdsEspAcuKiPod;
	}

	public void setPdsEspAcuKiPod(Integer pdsEspAcuKiPod) {
		this.pdsEspAcuKiPod = pdsEspAcuKiPod;
	}

	@Column(name = "PDS_ESP_ACU_KI_VOL")
	public Integer getPdsEspAcuKiVol() {
		return this.pdsEspAcuKiVol;
	}

	public void setPdsEspAcuKiVol(Integer pdsEspAcuKiVol) {
		this.pdsEspAcuKiVol = pdsEspAcuKiVol;
	}

	@Column(name = "PDS_CONOCIMIENTO_MARCIAL")
	public Integer getPdsConocimientoMarcial() {
		return this.pdsConocimientoMarcial;
	}

	public void setPdsConocimientoMarcial(Integer pdsConocimientoMarcial) {
		this.pdsConocimientoMarcial = pdsConocimientoMarcial;
	}

	@Column(name = "PDS_ESP_CONOCIMIENTO_MARCIAL")
	public Integer getPdsEspConocimientoMarcial() {
		return this.pdsEspConocimientoMarcial;
	}

	public void setPdsEspConocimientoMarcial(Integer pdsEspConocimientoMarcial) {
		this.pdsEspConocimientoMarcial = pdsEspConocimientoMarcial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdsPrimariasKi")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
