package modelo;
// Generated 16 jun. 2021 23:54:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PdsPrimariasComunes generated by hbm2java
 */
@Entity
@Table(name = "pds_primarias_comunes", catalog = "anima_sheets_data")
public class PdsPrimariasComunes implements java.io.Serializable {

	private int idPersonaje;
	private Personaje personaje;
	private Integer pdsHa;
	private Integer pdsHp;
	private Integer pdsHe;
	private Integer pdsLlevarArmadura;
	private Integer pdsEspHa;
	private Integer pdsEspHp;
	private Integer pdsEspHe;
	private Integer pdsEspLlevarArmadura;

	public PdsPrimariasComunes() {
	}

	public PdsPrimariasComunes(Personaje personaje) {
		this.personaje = personaje;
	}

	public PdsPrimariasComunes(Personaje personaje, Integer pdsHa, Integer pdsHp, Integer pdsHe,
			Integer pdsLlevarArmadura, Integer pdsEspHa, Integer pdsEspHp, Integer pdsEspHe,
			Integer pdsEspLlevarArmadura) {
		this.personaje = personaje;
		this.pdsHa = pdsHa;
		this.pdsHp = pdsHp;
		this.pdsHe = pdsHe;
		this.pdsLlevarArmadura = pdsLlevarArmadura;
		this.pdsEspHa = pdsEspHa;
		this.pdsEspHp = pdsEspHp;
		this.pdsEspHe = pdsEspHe;
		this.pdsEspLlevarArmadura = pdsEspLlevarArmadura;
	}

	@GenericGenerator(name = "modelo.PdsPrimariasComunesIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personaje"))
	@Id
	@GeneratedValue(generator = "modelo.PdsPrimariasComunesIdGenerator")

	@Column(name = "ID_PERSONAJE", unique = true, nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personaje getPersonaje() {
		return this.personaje;
	}

	public void setPersonaje(Personaje personaje) {
		this.personaje = personaje;
	}

	@Column(name = "PDS_HA")
	public Integer getPdsHa() {
		return this.pdsHa;
	}

	public void setPdsHa(Integer pdsHa) {
		this.pdsHa = pdsHa;
	}

	@Column(name = "PDS_HP")
	public Integer getPdsHp() {
		return this.pdsHp;
	}

	public void setPdsHp(Integer pdsHp) {
		this.pdsHp = pdsHp;
	}

	@Column(name = "PDS_HE")
	public Integer getPdsHe() {
		return this.pdsHe;
	}

	public void setPdsHe(Integer pdsHe) {
		this.pdsHe = pdsHe;
	}

	@Column(name = "PDS_LLEVAR_ARMADURA")
	public Integer getPdsLlevarArmadura() {
		return this.pdsLlevarArmadura;
	}

	public void setPdsLlevarArmadura(Integer pdsLlevarArmadura) {
		this.pdsLlevarArmadura = pdsLlevarArmadura;
	}

	@Column(name = "PDS_ESP_HA")
	public Integer getPdsEspHa() {
		return this.pdsEspHa;
	}

	public void setPdsEspHa(Integer pdsEspHa) {
		this.pdsEspHa = pdsEspHa;
	}

	@Column(name = "PDS_ESP_HP")
	public Integer getPdsEspHp() {
		return this.pdsEspHp;
	}

	public void setPdsEspHp(Integer pdsEspHp) {
		this.pdsEspHp = pdsEspHp;
	}

	@Column(name = "PDS_ESP_HE")
	public Integer getPdsEspHe() {
		return this.pdsEspHe;
	}

	public void setPdsEspHe(Integer pdsEspHe) {
		this.pdsEspHe = pdsEspHe;
	}

	@Column(name = "PDS_ESP_LLEVAR_ARMADURA")
	public Integer getPdsEspLlevarArmadura() {
		return this.pdsEspLlevarArmadura;
	}

	public void setPdsEspLlevarArmadura(Integer pdsEspLlevarArmadura) {
		this.pdsEspLlevarArmadura = pdsEspLlevarArmadura;
	}

}
