package modelo;
// Generated 16 jun. 2021 23:54:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PdsSecundariasSociales generated by hbm2java
 */
@Entity
@Table(name = "pds_secundarias_sociales", catalog = "anima_sheets_data")
public class PdsSecundariasSociales implements java.io.Serializable {

	private int idPersonaje;
	private Personaje personaje;
	private Integer pdsEstilo;
	private Integer pdsIntimidar;
	private Integer pdsLiderazgo;
	private Integer pdsPersuasion;
	private Integer pdsComercio;
	private Integer pdsCallejeo;
	private Integer pdsEtiqueta;
	private Integer pdsEspEstilo;
	private Integer pdsEspIntimidar;
	private Integer pdsEspLiderazgo;
	private Integer pdsEspPersuasion;
	private Integer pdsEspComercio;
	private Integer pdsEspCallejeo;
	private Integer pdsEspEtiqueta;
	private Integer bonoNaturalEstilo;
	private Integer bonoNaturalIntimidar;
	private Integer bonoNaturalLiderazgo;
	private Integer bonoNaturalPersuasion;
	private Integer bonoNaturalComercio;
	private Integer bonoNaturalCallejeo;
	private Integer bonoNaturalEtiqueta;
	private Integer habNaturalEstilo;
	private Integer habNaturalIntimidar;
	private Integer habNaturalLiderazgo;
	private Integer habNaturalPersuasion;
	private Integer habNaturalComercio;
	private Integer habNaturalCallejeo;
	private Integer habNaturalEtiqueta;
	private Integer bonoNovelEstilo;
	private Integer bonoNovelIntimidar;
	private Integer bonoNovelLiderazgo;
	private Integer bonoNovelPersuasion;
	private Integer bonoNovelComercio;
	private Integer bonoNovelCallejeo;
	private Integer bonoNovelEtiqueta;

	public PdsSecundariasSociales() {
	}

	public PdsSecundariasSociales(Personaje personaje) {
		this.personaje = personaje;
	}

	public PdsSecundariasSociales(Personaje personaje, Integer pdsEstilo, Integer pdsIntimidar, Integer pdsLiderazgo,
			Integer pdsPersuasion, Integer pdsComercio, Integer pdsCallejeo, Integer pdsEtiqueta, Integer pdsEspEstilo,
			Integer pdsEspIntimidar, Integer pdsEspLiderazgo, Integer pdsEspPersuasion, Integer pdsEspComercio,
			Integer pdsEspCallejeo, Integer pdsEspEtiqueta, Integer bonoNaturalEstilo, Integer bonoNaturalIntimidar,
			Integer bonoNaturalLiderazgo, Integer bonoNaturalPersuasion, Integer bonoNaturalComercio,
			Integer bonoNaturalCallejeo, Integer bonoNaturalEtiqueta, Integer habNaturalEstilo,
			Integer habNaturalIntimidar, Integer habNaturalLiderazgo, Integer habNaturalPersuasion,
			Integer habNaturalComercio, Integer habNaturalCallejeo, Integer habNaturalEtiqueta, Integer bonoNovelEstilo,
			Integer bonoNovelIntimidar, Integer bonoNovelLiderazgo, Integer bonoNovelPersuasion,
			Integer bonoNovelComercio, Integer bonoNovelCallejeo, Integer bonoNovelEtiqueta) {
		this.personaje = personaje;
		this.pdsEstilo = pdsEstilo;
		this.pdsIntimidar = pdsIntimidar;
		this.pdsLiderazgo = pdsLiderazgo;
		this.pdsPersuasion = pdsPersuasion;
		this.pdsComercio = pdsComercio;
		this.pdsCallejeo = pdsCallejeo;
		this.pdsEtiqueta = pdsEtiqueta;
		this.pdsEspEstilo = pdsEspEstilo;
		this.pdsEspIntimidar = pdsEspIntimidar;
		this.pdsEspLiderazgo = pdsEspLiderazgo;
		this.pdsEspPersuasion = pdsEspPersuasion;
		this.pdsEspComercio = pdsEspComercio;
		this.pdsEspCallejeo = pdsEspCallejeo;
		this.pdsEspEtiqueta = pdsEspEtiqueta;
		this.bonoNaturalEstilo = bonoNaturalEstilo;
		this.bonoNaturalIntimidar = bonoNaturalIntimidar;
		this.bonoNaturalLiderazgo = bonoNaturalLiderazgo;
		this.bonoNaturalPersuasion = bonoNaturalPersuasion;
		this.bonoNaturalComercio = bonoNaturalComercio;
		this.bonoNaturalCallejeo = bonoNaturalCallejeo;
		this.bonoNaturalEtiqueta = bonoNaturalEtiqueta;
		this.habNaturalEstilo = habNaturalEstilo;
		this.habNaturalIntimidar = habNaturalIntimidar;
		this.habNaturalLiderazgo = habNaturalLiderazgo;
		this.habNaturalPersuasion = habNaturalPersuasion;
		this.habNaturalComercio = habNaturalComercio;
		this.habNaturalCallejeo = habNaturalCallejeo;
		this.habNaturalEtiqueta = habNaturalEtiqueta;
		this.bonoNovelEstilo = bonoNovelEstilo;
		this.bonoNovelIntimidar = bonoNovelIntimidar;
		this.bonoNovelLiderazgo = bonoNovelLiderazgo;
		this.bonoNovelPersuasion = bonoNovelPersuasion;
		this.bonoNovelComercio = bonoNovelComercio;
		this.bonoNovelCallejeo = bonoNovelCallejeo;
		this.bonoNovelEtiqueta = bonoNovelEtiqueta;
	}

	@GenericGenerator(name = "modelo.PdsSecundariasSocialesIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personaje"))
	@Id
	@GeneratedValue(generator = "modelo.PdsSecundariasSocialesIdGenerator")

	@Column(name = "ID_PERSONAJE", unique = true, nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personaje getPersonaje() {
		return this.personaje;
	}

	public void setPersonaje(Personaje personaje) {
		this.personaje = personaje;
	}

	@Column(name = "PDS_ESTILO")
	public Integer getPdsEstilo() {
		return this.pdsEstilo;
	}

	public void setPdsEstilo(Integer pdsEstilo) {
		this.pdsEstilo = pdsEstilo;
	}

	@Column(name = "PDS_INTIMIDAR")
	public Integer getPdsIntimidar() {
		return this.pdsIntimidar;
	}

	public void setPdsIntimidar(Integer pdsIntimidar) {
		this.pdsIntimidar = pdsIntimidar;
	}

	@Column(name = "PDS_LIDERAZGO")
	public Integer getPdsLiderazgo() {
		return this.pdsLiderazgo;
	}

	public void setPdsLiderazgo(Integer pdsLiderazgo) {
		this.pdsLiderazgo = pdsLiderazgo;
	}

	@Column(name = "PDS_PERSUASION")
	public Integer getPdsPersuasion() {
		return this.pdsPersuasion;
	}

	public void setPdsPersuasion(Integer pdsPersuasion) {
		this.pdsPersuasion = pdsPersuasion;
	}

	@Column(name = "PDS_COMERCIO")
	public Integer getPdsComercio() {
		return this.pdsComercio;
	}

	public void setPdsComercio(Integer pdsComercio) {
		this.pdsComercio = pdsComercio;
	}

	@Column(name = "PDS_CALLEJEO")
	public Integer getPdsCallejeo() {
		return this.pdsCallejeo;
	}

	public void setPdsCallejeo(Integer pdsCallejeo) {
		this.pdsCallejeo = pdsCallejeo;
	}

	@Column(name = "PDS_ETIQUETA")
	public Integer getPdsEtiqueta() {
		return this.pdsEtiqueta;
	}

	public void setPdsEtiqueta(Integer pdsEtiqueta) {
		this.pdsEtiqueta = pdsEtiqueta;
	}

	@Column(name = "PDS_ESP_ESTILO")
	public Integer getPdsEspEstilo() {
		return this.pdsEspEstilo;
	}

	public void setPdsEspEstilo(Integer pdsEspEstilo) {
		this.pdsEspEstilo = pdsEspEstilo;
	}

	@Column(name = "PDS_ESP_INTIMIDAR")
	public Integer getPdsEspIntimidar() {
		return this.pdsEspIntimidar;
	}

	public void setPdsEspIntimidar(Integer pdsEspIntimidar) {
		this.pdsEspIntimidar = pdsEspIntimidar;
	}

	@Column(name = "PDS_ESP_LIDERAZGO")
	public Integer getPdsEspLiderazgo() {
		return this.pdsEspLiderazgo;
	}

	public void setPdsEspLiderazgo(Integer pdsEspLiderazgo) {
		this.pdsEspLiderazgo = pdsEspLiderazgo;
	}

	@Column(name = "PDS_ESP_PERSUASION")
	public Integer getPdsEspPersuasion() {
		return this.pdsEspPersuasion;
	}

	public void setPdsEspPersuasion(Integer pdsEspPersuasion) {
		this.pdsEspPersuasion = pdsEspPersuasion;
	}

	@Column(name = "PDS_ESP_COMERCIO")
	public Integer getPdsEspComercio() {
		return this.pdsEspComercio;
	}

	public void setPdsEspComercio(Integer pdsEspComercio) {
		this.pdsEspComercio = pdsEspComercio;
	}

	@Column(name = "PDS_ESP_CALLEJEO")
	public Integer getPdsEspCallejeo() {
		return this.pdsEspCallejeo;
	}

	public void setPdsEspCallejeo(Integer pdsEspCallejeo) {
		this.pdsEspCallejeo = pdsEspCallejeo;
	}

	@Column(name = "PDS_ESP_ETIQUETA")
	public Integer getPdsEspEtiqueta() {
		return this.pdsEspEtiqueta;
	}

	public void setPdsEspEtiqueta(Integer pdsEspEtiqueta) {
		this.pdsEspEtiqueta = pdsEspEtiqueta;
	}

	@Column(name = "BONO_NATURAL_ESTILO")
	public Integer getBonoNaturalEstilo() {
		return this.bonoNaturalEstilo;
	}

	public void setBonoNaturalEstilo(Integer bonoNaturalEstilo) {
		this.bonoNaturalEstilo = bonoNaturalEstilo;
	}

	@Column(name = "BONO_NATURAL_INTIMIDAR")
	public Integer getBonoNaturalIntimidar() {
		return this.bonoNaturalIntimidar;
	}

	public void setBonoNaturalIntimidar(Integer bonoNaturalIntimidar) {
		this.bonoNaturalIntimidar = bonoNaturalIntimidar;
	}

	@Column(name = "BONO_NATURAL_LIDERAZGO")
	public Integer getBonoNaturalLiderazgo() {
		return this.bonoNaturalLiderazgo;
	}

	public void setBonoNaturalLiderazgo(Integer bonoNaturalLiderazgo) {
		this.bonoNaturalLiderazgo = bonoNaturalLiderazgo;
	}

	@Column(name = "BONO_NATURAL_PERSUASION")
	public Integer getBonoNaturalPersuasion() {
		return this.bonoNaturalPersuasion;
	}

	public void setBonoNaturalPersuasion(Integer bonoNaturalPersuasion) {
		this.bonoNaturalPersuasion = bonoNaturalPersuasion;
	}

	@Column(name = "BONO_NATURAL_COMERCIO")
	public Integer getBonoNaturalComercio() {
		return this.bonoNaturalComercio;
	}

	public void setBonoNaturalComercio(Integer bonoNaturalComercio) {
		this.bonoNaturalComercio = bonoNaturalComercio;
	}

	@Column(name = "BONO_NATURAL_CALLEJEO")
	public Integer getBonoNaturalCallejeo() {
		return this.bonoNaturalCallejeo;
	}

	public void setBonoNaturalCallejeo(Integer bonoNaturalCallejeo) {
		this.bonoNaturalCallejeo = bonoNaturalCallejeo;
	}

	@Column(name = "BONO_NATURAL_ETIQUETA")
	public Integer getBonoNaturalEtiqueta() {
		return this.bonoNaturalEtiqueta;
	}

	public void setBonoNaturalEtiqueta(Integer bonoNaturalEtiqueta) {
		this.bonoNaturalEtiqueta = bonoNaturalEtiqueta;
	}

	@Column(name = "HAB_NATURAL_ESTILO")
	public Integer getHabNaturalEstilo() {
		return this.habNaturalEstilo;
	}

	public void setHabNaturalEstilo(Integer habNaturalEstilo) {
		this.habNaturalEstilo = habNaturalEstilo;
	}

	@Column(name = "HAB_NATURAL_INTIMIDAR")
	public Integer getHabNaturalIntimidar() {
		return this.habNaturalIntimidar;
	}

	public void setHabNaturalIntimidar(Integer habNaturalIntimidar) {
		this.habNaturalIntimidar = habNaturalIntimidar;
	}

	@Column(name = "HAB_NATURAL_LIDERAZGO")
	public Integer getHabNaturalLiderazgo() {
		return this.habNaturalLiderazgo;
	}

	public void setHabNaturalLiderazgo(Integer habNaturalLiderazgo) {
		this.habNaturalLiderazgo = habNaturalLiderazgo;
	}

	@Column(name = "HAB_NATURAL_PERSUASION")
	public Integer getHabNaturalPersuasion() {
		return this.habNaturalPersuasion;
	}

	public void setHabNaturalPersuasion(Integer habNaturalPersuasion) {
		this.habNaturalPersuasion = habNaturalPersuasion;
	}

	@Column(name = "HAB_NATURAL_COMERCIO")
	public Integer getHabNaturalComercio() {
		return this.habNaturalComercio;
	}

	public void setHabNaturalComercio(Integer habNaturalComercio) {
		this.habNaturalComercio = habNaturalComercio;
	}

	@Column(name = "HAB_NATURAL_CALLEJEO")
	public Integer getHabNaturalCallejeo() {
		return this.habNaturalCallejeo;
	}

	public void setHabNaturalCallejeo(Integer habNaturalCallejeo) {
		this.habNaturalCallejeo = habNaturalCallejeo;
	}

	@Column(name = "HAB_NATURAL_ETIQUETA")
	public Integer getHabNaturalEtiqueta() {
		return this.habNaturalEtiqueta;
	}

	public void setHabNaturalEtiqueta(Integer habNaturalEtiqueta) {
		this.habNaturalEtiqueta = habNaturalEtiqueta;
	}

	@Column(name = "BONO_NOVEL_ESTILO")
	public Integer getBonoNovelEstilo() {
		return this.bonoNovelEstilo;
	}

	public void setBonoNovelEstilo(Integer bonoNovelEstilo) {
		this.bonoNovelEstilo = bonoNovelEstilo;
	}

	@Column(name = "BONO_NOVEL_INTIMIDAR")
	public Integer getBonoNovelIntimidar() {
		return this.bonoNovelIntimidar;
	}

	public void setBonoNovelIntimidar(Integer bonoNovelIntimidar) {
		this.bonoNovelIntimidar = bonoNovelIntimidar;
	}

	@Column(name = "BONO_NOVEL_LIDERAZGO")
	public Integer getBonoNovelLiderazgo() {
		return this.bonoNovelLiderazgo;
	}

	public void setBonoNovelLiderazgo(Integer bonoNovelLiderazgo) {
		this.bonoNovelLiderazgo = bonoNovelLiderazgo;
	}

	@Column(name = "BONO_NOVEL_PERSUASION")
	public Integer getBonoNovelPersuasion() {
		return this.bonoNovelPersuasion;
	}

	public void setBonoNovelPersuasion(Integer bonoNovelPersuasion) {
		this.bonoNovelPersuasion = bonoNovelPersuasion;
	}

	@Column(name = "BONO_NOVEL_COMERCIO")
	public Integer getBonoNovelComercio() {
		return this.bonoNovelComercio;
	}

	public void setBonoNovelComercio(Integer bonoNovelComercio) {
		this.bonoNovelComercio = bonoNovelComercio;
	}

	@Column(name = "BONO_NOVEL_CALLEJEO")
	public Integer getBonoNovelCallejeo() {
		return this.bonoNovelCallejeo;
	}

	public void setBonoNovelCallejeo(Integer bonoNovelCallejeo) {
		this.bonoNovelCallejeo = bonoNovelCallejeo;
	}

	@Column(name = "BONO_NOVEL_ETIQUETA")
	public Integer getBonoNovelEtiqueta() {
		return this.bonoNovelEtiqueta;
	}

	public void setBonoNovelEtiqueta(Integer bonoNovelEtiqueta) {
		this.bonoNovelEtiqueta = bonoNovelEtiqueta;
	}

}
