package modelo;
// Generated 24 may. 2021 13:40:54 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PdsSecundariasPerceptivas generated by hbm2java
 */
@Entity
@Table(name = "pds_secundarias_perceptivas", catalog = "anima_sheets_data")
public class PdsSecundariasPerceptivas implements java.io.Serializable {

	private int pdsSecundariasPerceptivas;
	private Integer pdsAdvertir;
	private Integer pdsBuscar;
	private Integer pdsRestrear;
	private Integer pdsEspAdvertir;
	private Integer pdsEspBuscar;
	private Integer pdsEspRestrear;
	private Integer bonoNaturalAdvertir;
	private Integer bonoNaturalBuscar;
	private Integer bonoNaturalRestrear;
	private Integer habNaturalAdvertir;
	private Integer habNaturalBuscar;
	private Integer habNaturalRestrear;
	private Integer bonoNovelAdvertir;
	private Integer bonoNovelBuscar;
	private Integer bonoNovelRestrear;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public PdsSecundariasPerceptivas() {
	}

	public PdsSecundariasPerceptivas(int pdsSecundariasPerceptivas) {
		this.pdsSecundariasPerceptivas = pdsSecundariasPerceptivas;
	}

	public PdsSecundariasPerceptivas(int pdsSecundariasPerceptivas, Integer pdsAdvertir, Integer pdsBuscar,
			Integer pdsRestrear, Integer pdsEspAdvertir, Integer pdsEspBuscar, Integer pdsEspRestrear,
			Integer bonoNaturalAdvertir, Integer bonoNaturalBuscar, Integer bonoNaturalRestrear,
			Integer habNaturalAdvertir, Integer habNaturalBuscar, Integer habNaturalRestrear, Integer bonoNovelAdvertir,
			Integer bonoNovelBuscar, Integer bonoNovelRestrear, Set<PdsCategoria> pdsCategorias) {
		this.pdsSecundariasPerceptivas = pdsSecundariasPerceptivas;
		this.pdsAdvertir = pdsAdvertir;
		this.pdsBuscar = pdsBuscar;
		this.pdsRestrear = pdsRestrear;
		this.pdsEspAdvertir = pdsEspAdvertir;
		this.pdsEspBuscar = pdsEspBuscar;
		this.pdsEspRestrear = pdsEspRestrear;
		this.bonoNaturalAdvertir = bonoNaturalAdvertir;
		this.bonoNaturalBuscar = bonoNaturalBuscar;
		this.bonoNaturalRestrear = bonoNaturalRestrear;
		this.habNaturalAdvertir = habNaturalAdvertir;
		this.habNaturalBuscar = habNaturalBuscar;
		this.habNaturalRestrear = habNaturalRestrear;
		this.bonoNovelAdvertir = bonoNovelAdvertir;
		this.bonoNovelBuscar = bonoNovelBuscar;
		this.bonoNovelRestrear = bonoNovelRestrear;
		this.pdsCategorias = pdsCategorias;
	}

	@Id

	@Column(name = "PDS_SECUNDARIAS_PERCEPTIVAS", unique = true, nullable = false)
	public int getPdsSecundariasPerceptivas() {
		return this.pdsSecundariasPerceptivas;
	}

	public void setPdsSecundariasPerceptivas(int pdsSecundariasPerceptivas) {
		this.pdsSecundariasPerceptivas = pdsSecundariasPerceptivas;
	}

	@Column(name = "PDS_ADVERTIR")
	public Integer getPdsAdvertir() {
		return this.pdsAdvertir;
	}

	public void setPdsAdvertir(Integer pdsAdvertir) {
		this.pdsAdvertir = pdsAdvertir;
	}

	@Column(name = "PDS_BUSCAR")
	public Integer getPdsBuscar() {
		return this.pdsBuscar;
	}

	public void setPdsBuscar(Integer pdsBuscar) {
		this.pdsBuscar = pdsBuscar;
	}

	@Column(name = "PDS_RESTREAR")
	public Integer getPdsRestrear() {
		return this.pdsRestrear;
	}

	public void setPdsRestrear(Integer pdsRestrear) {
		this.pdsRestrear = pdsRestrear;
	}

	@Column(name = "PDS_ESP_ADVERTIR")
	public Integer getPdsEspAdvertir() {
		return this.pdsEspAdvertir;
	}

	public void setPdsEspAdvertir(Integer pdsEspAdvertir) {
		this.pdsEspAdvertir = pdsEspAdvertir;
	}

	@Column(name = "PDS_ESP_BUSCAR")
	public Integer getPdsEspBuscar() {
		return this.pdsEspBuscar;
	}

	public void setPdsEspBuscar(Integer pdsEspBuscar) {
		this.pdsEspBuscar = pdsEspBuscar;
	}

	@Column(name = "PDS_ESP_RESTREAR")
	public Integer getPdsEspRestrear() {
		return this.pdsEspRestrear;
	}

	public void setPdsEspRestrear(Integer pdsEspRestrear) {
		this.pdsEspRestrear = pdsEspRestrear;
	}

	@Column(name = "BONO_NATURAL_ADVERTIR")
	public Integer getBonoNaturalAdvertir() {
		return this.bonoNaturalAdvertir;
	}

	public void setBonoNaturalAdvertir(Integer bonoNaturalAdvertir) {
		this.bonoNaturalAdvertir = bonoNaturalAdvertir;
	}

	@Column(name = "BONO_NATURAL_BUSCAR")
	public Integer getBonoNaturalBuscar() {
		return this.bonoNaturalBuscar;
	}

	public void setBonoNaturalBuscar(Integer bonoNaturalBuscar) {
		this.bonoNaturalBuscar = bonoNaturalBuscar;
	}

	@Column(name = "BONO_NATURAL_RESTREAR")
	public Integer getBonoNaturalRestrear() {
		return this.bonoNaturalRestrear;
	}

	public void setBonoNaturalRestrear(Integer bonoNaturalRestrear) {
		this.bonoNaturalRestrear = bonoNaturalRestrear;
	}

	@Column(name = "HAB_NATURAL_ADVERTIR")
	public Integer getHabNaturalAdvertir() {
		return this.habNaturalAdvertir;
	}

	public void setHabNaturalAdvertir(Integer habNaturalAdvertir) {
		this.habNaturalAdvertir = habNaturalAdvertir;
	}

	@Column(name = "HAB_NATURAL_BUSCAR")
	public Integer getHabNaturalBuscar() {
		return this.habNaturalBuscar;
	}

	public void setHabNaturalBuscar(Integer habNaturalBuscar) {
		this.habNaturalBuscar = habNaturalBuscar;
	}

	@Column(name = "HAB_NATURAL_RESTREAR")
	public Integer getHabNaturalRestrear() {
		return this.habNaturalRestrear;
	}

	public void setHabNaturalRestrear(Integer habNaturalRestrear) {
		this.habNaturalRestrear = habNaturalRestrear;
	}

	@Column(name = "BONO_NOVEL_ADVERTIR")
	public Integer getBonoNovelAdvertir() {
		return this.bonoNovelAdvertir;
	}

	public void setBonoNovelAdvertir(Integer bonoNovelAdvertir) {
		this.bonoNovelAdvertir = bonoNovelAdvertir;
	}

	@Column(name = "BONO_NOVEL_BUSCAR")
	public Integer getBonoNovelBuscar() {
		return this.bonoNovelBuscar;
	}

	public void setBonoNovelBuscar(Integer bonoNovelBuscar) {
		this.bonoNovelBuscar = bonoNovelBuscar;
	}

	@Column(name = "BONO_NOVEL_RESTREAR")
	public Integer getBonoNovelRestrear() {
		return this.bonoNovelRestrear;
	}

	public void setBonoNovelRestrear(Integer bonoNovelRestrear) {
		this.bonoNovelRestrear = bonoNovelRestrear;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdsSecundariasPerceptivas")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
