package modelo;
// Generated 15 jun. 2021 23:20:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PdsSecundariasIntelectuales generated by hbm2java
 */
@Entity
@Table(name = "pds_secundarias_intelectuales", catalog = "anima_sheets_data")
public class PdsSecundariasIntelectuales implements java.io.Serializable {

	private int pdsSecundariasIntelectuales;
	private Integer pdsAnimales;
	private Integer pdsCiencia;
	private Integer pdsLey;
	private Integer pdsHerbolaria;
	private Integer pdsHistoria;
	private Integer pdsTactica;
	private Integer pdsMedicina;
	private Integer pdsMemorizar;
	private Integer pdsNavegacion;
	private Integer pdsOcultismo;
	private Integer pdsTasacion;
	private Integer pdsValoracionMagica;
	private Integer pdsEspAnimales;
	private Integer pdsEspCiencia;
	private Integer pdsEspLey;
	private Integer pdsEspHerbolaria;
	private Integer pdsEspHistoria;
	private Integer pdsEspTactica;
	private Integer pdsEspMedicina;
	private Integer pdsEspMemorizar;
	private Integer pdsEspNavegacion;
	private Integer pdsEspOcultismo;
	private Integer pdsEspTasacion;
	private Integer pdsEspValoracionMagica;
	private Integer bonoNaturalAnimales;
	private Integer bonoNaturalCiencia;
	private Integer bonoNaturalLey;
	private Integer bonoNaturalHerbolaria;
	private Integer bonoNaturalHistoria;
	private Integer bonoNaturalTactica;
	private Integer bonoNaturalMedicina;
	private Integer bonoNaturalMemorizar;
	private Integer bonoNaturalNavegacion;
	private Integer bonoNaturalOcultismo;
	private Integer bonoNaturalTasacion;
	private Integer bonoNaturalValoracionMagica;
	private Integer habNaturalAnimales;
	private Integer habNaturalCiencia;
	private Integer habNaturalLey;
	private Integer habNaturalHerbolaria;
	private Integer habNaturalHistoria;
	private Integer habNaturalTactica;
	private Integer habNaturalMedicina;
	private Integer habNaturalMemorizar;
	private Integer habNaturalNavegacion;
	private Integer habNaturalOcultismo;
	private Integer habNaturalTasacion;
	private Integer habNaturalValoracionMagica;
	private Integer bonoNovelAnimales;
	private Integer bonoNovelCiencia;
	private Integer bonoNovelLey;
	private Integer bonoNovelHerbolaria;
	private Integer bonoNovelHistoria;
	private Integer bonoNovelTactica;
	private Integer bonoNovelMedicina;
	private Integer bonoNovelMemorizar;
	private Integer bonoNovelNavegacion;
	private Integer bonoNovelOcultismo;
	private Integer bonoNovelTasacion;
	private Integer bonoNovelValoracionMagica;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public PdsSecundariasIntelectuales() {
	}

	public PdsSecundariasIntelectuales(int pdsSecundariasIntelectuales) {
		this.pdsSecundariasIntelectuales = pdsSecundariasIntelectuales;
	}

	public PdsSecundariasIntelectuales(int pdsSecundariasIntelectuales, Integer pdsAnimales, Integer pdsCiencia,
			Integer pdsLey, Integer pdsHerbolaria, Integer pdsHistoria, Integer pdsTactica, Integer pdsMedicina,
			Integer pdsMemorizar, Integer pdsNavegacion, Integer pdsOcultismo, Integer pdsTasacion,
			Integer pdsValoracionMagica, Integer pdsEspAnimales, Integer pdsEspCiencia, Integer pdsEspLey,
			Integer pdsEspHerbolaria, Integer pdsEspHistoria, Integer pdsEspTactica, Integer pdsEspMedicina,
			Integer pdsEspMemorizar, Integer pdsEspNavegacion, Integer pdsEspOcultismo, Integer pdsEspTasacion,
			Integer pdsEspValoracionMagica, Integer bonoNaturalAnimales, Integer bonoNaturalCiencia,
			Integer bonoNaturalLey, Integer bonoNaturalHerbolaria, Integer bonoNaturalHistoria,
			Integer bonoNaturalTactica, Integer bonoNaturalMedicina, Integer bonoNaturalMemorizar,
			Integer bonoNaturalNavegacion, Integer bonoNaturalOcultismo, Integer bonoNaturalTasacion,
			Integer bonoNaturalValoracionMagica, Integer habNaturalAnimales, Integer habNaturalCiencia,
			Integer habNaturalLey, Integer habNaturalHerbolaria, Integer habNaturalHistoria, Integer habNaturalTactica,
			Integer habNaturalMedicina, Integer habNaturalMemorizar, Integer habNaturalNavegacion,
			Integer habNaturalOcultismo, Integer habNaturalTasacion, Integer habNaturalValoracionMagica,
			Integer bonoNovelAnimales, Integer bonoNovelCiencia, Integer bonoNovelLey, Integer bonoNovelHerbolaria,
			Integer bonoNovelHistoria, Integer bonoNovelTactica, Integer bonoNovelMedicina, Integer bonoNovelMemorizar,
			Integer bonoNovelNavegacion, Integer bonoNovelOcultismo, Integer bonoNovelTasacion,
			Integer bonoNovelValoracionMagica, Set<PdsCategoria> pdsCategorias) {
		this.pdsSecundariasIntelectuales = pdsSecundariasIntelectuales;
		this.pdsAnimales = pdsAnimales;
		this.pdsCiencia = pdsCiencia;
		this.pdsLey = pdsLey;
		this.pdsHerbolaria = pdsHerbolaria;
		this.pdsHistoria = pdsHistoria;
		this.pdsTactica = pdsTactica;
		this.pdsMedicina = pdsMedicina;
		this.pdsMemorizar = pdsMemorizar;
		this.pdsNavegacion = pdsNavegacion;
		this.pdsOcultismo = pdsOcultismo;
		this.pdsTasacion = pdsTasacion;
		this.pdsValoracionMagica = pdsValoracionMagica;
		this.pdsEspAnimales = pdsEspAnimales;
		this.pdsEspCiencia = pdsEspCiencia;
		this.pdsEspLey = pdsEspLey;
		this.pdsEspHerbolaria = pdsEspHerbolaria;
		this.pdsEspHistoria = pdsEspHistoria;
		this.pdsEspTactica = pdsEspTactica;
		this.pdsEspMedicina = pdsEspMedicina;
		this.pdsEspMemorizar = pdsEspMemorizar;
		this.pdsEspNavegacion = pdsEspNavegacion;
		this.pdsEspOcultismo = pdsEspOcultismo;
		this.pdsEspTasacion = pdsEspTasacion;
		this.pdsEspValoracionMagica = pdsEspValoracionMagica;
		this.bonoNaturalAnimales = bonoNaturalAnimales;
		this.bonoNaturalCiencia = bonoNaturalCiencia;
		this.bonoNaturalLey = bonoNaturalLey;
		this.bonoNaturalHerbolaria = bonoNaturalHerbolaria;
		this.bonoNaturalHistoria = bonoNaturalHistoria;
		this.bonoNaturalTactica = bonoNaturalTactica;
		this.bonoNaturalMedicina = bonoNaturalMedicina;
		this.bonoNaturalMemorizar = bonoNaturalMemorizar;
		this.bonoNaturalNavegacion = bonoNaturalNavegacion;
		this.bonoNaturalOcultismo = bonoNaturalOcultismo;
		this.bonoNaturalTasacion = bonoNaturalTasacion;
		this.bonoNaturalValoracionMagica = bonoNaturalValoracionMagica;
		this.habNaturalAnimales = habNaturalAnimales;
		this.habNaturalCiencia = habNaturalCiencia;
		this.habNaturalLey = habNaturalLey;
		this.habNaturalHerbolaria = habNaturalHerbolaria;
		this.habNaturalHistoria = habNaturalHistoria;
		this.habNaturalTactica = habNaturalTactica;
		this.habNaturalMedicina = habNaturalMedicina;
		this.habNaturalMemorizar = habNaturalMemorizar;
		this.habNaturalNavegacion = habNaturalNavegacion;
		this.habNaturalOcultismo = habNaturalOcultismo;
		this.habNaturalTasacion = habNaturalTasacion;
		this.habNaturalValoracionMagica = habNaturalValoracionMagica;
		this.bonoNovelAnimales = bonoNovelAnimales;
		this.bonoNovelCiencia = bonoNovelCiencia;
		this.bonoNovelLey = bonoNovelLey;
		this.bonoNovelHerbolaria = bonoNovelHerbolaria;
		this.bonoNovelHistoria = bonoNovelHistoria;
		this.bonoNovelTactica = bonoNovelTactica;
		this.bonoNovelMedicina = bonoNovelMedicina;
		this.bonoNovelMemorizar = bonoNovelMemorizar;
		this.bonoNovelNavegacion = bonoNovelNavegacion;
		this.bonoNovelOcultismo = bonoNovelOcultismo;
		this.bonoNovelTasacion = bonoNovelTasacion;
		this.bonoNovelValoracionMagica = bonoNovelValoracionMagica;
		this.pdsCategorias = pdsCategorias;
	}

	@Id

	@Column(name = "PDS_SECUNDARIAS_INTELECTUALES", unique = true, nullable = false)
	public int getPdsSecundariasIntelectuales() {
		return this.pdsSecundariasIntelectuales;
	}

	public void setPdsSecundariasIntelectuales(int pdsSecundariasIntelectuales) {
		this.pdsSecundariasIntelectuales = pdsSecundariasIntelectuales;
	}

	@Column(name = "PDS_ANIMALES")
	public Integer getPdsAnimales() {
		return this.pdsAnimales;
	}

	public void setPdsAnimales(Integer pdsAnimales) {
		this.pdsAnimales = pdsAnimales;
	}

	@Column(name = "PDS_CIENCIA")
	public Integer getPdsCiencia() {
		return this.pdsCiencia;
	}

	public void setPdsCiencia(Integer pdsCiencia) {
		this.pdsCiencia = pdsCiencia;
	}

	@Column(name = "PDS_LEY")
	public Integer getPdsLey() {
		return this.pdsLey;
	}

	public void setPdsLey(Integer pdsLey) {
		this.pdsLey = pdsLey;
	}

	@Column(name = "PDS_HERBOLARIA")
	public Integer getPdsHerbolaria() {
		return this.pdsHerbolaria;
	}

	public void setPdsHerbolaria(Integer pdsHerbolaria) {
		this.pdsHerbolaria = pdsHerbolaria;
	}

	@Column(name = "PDS_HISTORIA")
	public Integer getPdsHistoria() {
		return this.pdsHistoria;
	}

	public void setPdsHistoria(Integer pdsHistoria) {
		this.pdsHistoria = pdsHistoria;
	}

	@Column(name = "PDS_TACTICA")
	public Integer getPdsTactica() {
		return this.pdsTactica;
	}

	public void setPdsTactica(Integer pdsTactica) {
		this.pdsTactica = pdsTactica;
	}

	@Column(name = "PDS_MEDICINA")
	public Integer getPdsMedicina() {
		return this.pdsMedicina;
	}

	public void setPdsMedicina(Integer pdsMedicina) {
		this.pdsMedicina = pdsMedicina;
	}

	@Column(name = "PDS_MEMORIZAR")
	public Integer getPdsMemorizar() {
		return this.pdsMemorizar;
	}

	public void setPdsMemorizar(Integer pdsMemorizar) {
		this.pdsMemorizar = pdsMemorizar;
	}

	@Column(name = "PDS_NAVEGACION")
	public Integer getPdsNavegacion() {
		return this.pdsNavegacion;
	}

	public void setPdsNavegacion(Integer pdsNavegacion) {
		this.pdsNavegacion = pdsNavegacion;
	}

	@Column(name = "PDS_OCULTISMO")
	public Integer getPdsOcultismo() {
		return this.pdsOcultismo;
	}

	public void setPdsOcultismo(Integer pdsOcultismo) {
		this.pdsOcultismo = pdsOcultismo;
	}

	@Column(name = "PDS_TASACION")
	public Integer getPdsTasacion() {
		return this.pdsTasacion;
	}

	public void setPdsTasacion(Integer pdsTasacion) {
		this.pdsTasacion = pdsTasacion;
	}

	@Column(name = "PDS_VALORACION_MAGICA")
	public Integer getPdsValoracionMagica() {
		return this.pdsValoracionMagica;
	}

	public void setPdsValoracionMagica(Integer pdsValoracionMagica) {
		this.pdsValoracionMagica = pdsValoracionMagica;
	}

	@Column(name = "PDS_ESP_ANIMALES")
	public Integer getPdsEspAnimales() {
		return this.pdsEspAnimales;
	}

	public void setPdsEspAnimales(Integer pdsEspAnimales) {
		this.pdsEspAnimales = pdsEspAnimales;
	}

	@Column(name = "PDS_ESP_CIENCIA")
	public Integer getPdsEspCiencia() {
		return this.pdsEspCiencia;
	}

	public void setPdsEspCiencia(Integer pdsEspCiencia) {
		this.pdsEspCiencia = pdsEspCiencia;
	}

	@Column(name = "PDS_ESP_LEY")
	public Integer getPdsEspLey() {
		return this.pdsEspLey;
	}

	public void setPdsEspLey(Integer pdsEspLey) {
		this.pdsEspLey = pdsEspLey;
	}

	@Column(name = "PDS_ESP_HERBOLARIA")
	public Integer getPdsEspHerbolaria() {
		return this.pdsEspHerbolaria;
	}

	public void setPdsEspHerbolaria(Integer pdsEspHerbolaria) {
		this.pdsEspHerbolaria = pdsEspHerbolaria;
	}

	@Column(name = "PDS_ESP_HISTORIA")
	public Integer getPdsEspHistoria() {
		return this.pdsEspHistoria;
	}

	public void setPdsEspHistoria(Integer pdsEspHistoria) {
		this.pdsEspHistoria = pdsEspHistoria;
	}

	@Column(name = "PDS_ESP_TACTICA")
	public Integer getPdsEspTactica() {
		return this.pdsEspTactica;
	}

	public void setPdsEspTactica(Integer pdsEspTactica) {
		this.pdsEspTactica = pdsEspTactica;
	}

	@Column(name = "PDS_ESP_MEDICINA")
	public Integer getPdsEspMedicina() {
		return this.pdsEspMedicina;
	}

	public void setPdsEspMedicina(Integer pdsEspMedicina) {
		this.pdsEspMedicina = pdsEspMedicina;
	}

	@Column(name = "PDS_ESP_MEMORIZAR")
	public Integer getPdsEspMemorizar() {
		return this.pdsEspMemorizar;
	}

	public void setPdsEspMemorizar(Integer pdsEspMemorizar) {
		this.pdsEspMemorizar = pdsEspMemorizar;
	}

	@Column(name = "PDS_ESP_NAVEGACION")
	public Integer getPdsEspNavegacion() {
		return this.pdsEspNavegacion;
	}

	public void setPdsEspNavegacion(Integer pdsEspNavegacion) {
		this.pdsEspNavegacion = pdsEspNavegacion;
	}

	@Column(name = "PDS_ESP_OCULTISMO")
	public Integer getPdsEspOcultismo() {
		return this.pdsEspOcultismo;
	}

	public void setPdsEspOcultismo(Integer pdsEspOcultismo) {
		this.pdsEspOcultismo = pdsEspOcultismo;
	}

	@Column(name = "PDS_ESP_TASACION")
	public Integer getPdsEspTasacion() {
		return this.pdsEspTasacion;
	}

	public void setPdsEspTasacion(Integer pdsEspTasacion) {
		this.pdsEspTasacion = pdsEspTasacion;
	}

	@Column(name = "PDS_ESP_VALORACION_MAGICA")
	public Integer getPdsEspValoracionMagica() {
		return this.pdsEspValoracionMagica;
	}

	public void setPdsEspValoracionMagica(Integer pdsEspValoracionMagica) {
		this.pdsEspValoracionMagica = pdsEspValoracionMagica;
	}

	@Column(name = "BONO_NATURAL_ANIMALES")
	public Integer getBonoNaturalAnimales() {
		return this.bonoNaturalAnimales;
	}

	public void setBonoNaturalAnimales(Integer bonoNaturalAnimales) {
		this.bonoNaturalAnimales = bonoNaturalAnimales;
	}

	@Column(name = "BONO_NATURAL_CIENCIA")
	public Integer getBonoNaturalCiencia() {
		return this.bonoNaturalCiencia;
	}

	public void setBonoNaturalCiencia(Integer bonoNaturalCiencia) {
		this.bonoNaturalCiencia = bonoNaturalCiencia;
	}

	@Column(name = "BONO_NATURAL_LEY")
	public Integer getBonoNaturalLey() {
		return this.bonoNaturalLey;
	}

	public void setBonoNaturalLey(Integer bonoNaturalLey) {
		this.bonoNaturalLey = bonoNaturalLey;
	}

	@Column(name = "BONO_NATURAL_HERBOLARIA")
	public Integer getBonoNaturalHerbolaria() {
		return this.bonoNaturalHerbolaria;
	}

	public void setBonoNaturalHerbolaria(Integer bonoNaturalHerbolaria) {
		this.bonoNaturalHerbolaria = bonoNaturalHerbolaria;
	}

	@Column(name = "BONO_NATURAL_HISTORIA")
	public Integer getBonoNaturalHistoria() {
		return this.bonoNaturalHistoria;
	}

	public void setBonoNaturalHistoria(Integer bonoNaturalHistoria) {
		this.bonoNaturalHistoria = bonoNaturalHistoria;
	}

	@Column(name = "BONO_NATURAL_TACTICA")
	public Integer getBonoNaturalTactica() {
		return this.bonoNaturalTactica;
	}

	public void setBonoNaturalTactica(Integer bonoNaturalTactica) {
		this.bonoNaturalTactica = bonoNaturalTactica;
	}

	@Column(name = "BONO_NATURAL_MEDICINA")
	public Integer getBonoNaturalMedicina() {
		return this.bonoNaturalMedicina;
	}

	public void setBonoNaturalMedicina(Integer bonoNaturalMedicina) {
		this.bonoNaturalMedicina = bonoNaturalMedicina;
	}

	@Column(name = "BONO_NATURAL_MEMORIZAR")
	public Integer getBonoNaturalMemorizar() {
		return this.bonoNaturalMemorizar;
	}

	public void setBonoNaturalMemorizar(Integer bonoNaturalMemorizar) {
		this.bonoNaturalMemorizar = bonoNaturalMemorizar;
	}

	@Column(name = "BONO_NATURAL_NAVEGACION")
	public Integer getBonoNaturalNavegacion() {
		return this.bonoNaturalNavegacion;
	}

	public void setBonoNaturalNavegacion(Integer bonoNaturalNavegacion) {
		this.bonoNaturalNavegacion = bonoNaturalNavegacion;
	}

	@Column(name = "BONO_NATURAL_OCULTISMO")
	public Integer getBonoNaturalOcultismo() {
		return this.bonoNaturalOcultismo;
	}

	public void setBonoNaturalOcultismo(Integer bonoNaturalOcultismo) {
		this.bonoNaturalOcultismo = bonoNaturalOcultismo;
	}

	@Column(name = "BONO_NATURAL_TASACION")
	public Integer getBonoNaturalTasacion() {
		return this.bonoNaturalTasacion;
	}

	public void setBonoNaturalTasacion(Integer bonoNaturalTasacion) {
		this.bonoNaturalTasacion = bonoNaturalTasacion;
	}

	@Column(name = "BONO_NATURAL_VALORACION_MAGICA")
	public Integer getBonoNaturalValoracionMagica() {
		return this.bonoNaturalValoracionMagica;
	}

	public void setBonoNaturalValoracionMagica(Integer bonoNaturalValoracionMagica) {
		this.bonoNaturalValoracionMagica = bonoNaturalValoracionMagica;
	}

	@Column(name = "HAB_NATURAL_ANIMALES")
	public Integer getHabNaturalAnimales() {
		return this.habNaturalAnimales;
	}

	public void setHabNaturalAnimales(Integer habNaturalAnimales) {
		this.habNaturalAnimales = habNaturalAnimales;
	}

	@Column(name = "HAB_NATURAL_CIENCIA")
	public Integer getHabNaturalCiencia() {
		return this.habNaturalCiencia;
	}

	public void setHabNaturalCiencia(Integer habNaturalCiencia) {
		this.habNaturalCiencia = habNaturalCiencia;
	}

	@Column(name = "HAB_NATURAL_LEY")
	public Integer getHabNaturalLey() {
		return this.habNaturalLey;
	}

	public void setHabNaturalLey(Integer habNaturalLey) {
		this.habNaturalLey = habNaturalLey;
	}

	@Column(name = "HAB_NATURAL_HERBOLARIA")
	public Integer getHabNaturalHerbolaria() {
		return this.habNaturalHerbolaria;
	}

	public void setHabNaturalHerbolaria(Integer habNaturalHerbolaria) {
		this.habNaturalHerbolaria = habNaturalHerbolaria;
	}

	@Column(name = "HAB_NATURAL_HISTORIA")
	public Integer getHabNaturalHistoria() {
		return this.habNaturalHistoria;
	}

	public void setHabNaturalHistoria(Integer habNaturalHistoria) {
		this.habNaturalHistoria = habNaturalHistoria;
	}

	@Column(name = "HAB_NATURAL_TACTICA")
	public Integer getHabNaturalTactica() {
		return this.habNaturalTactica;
	}

	public void setHabNaturalTactica(Integer habNaturalTactica) {
		this.habNaturalTactica = habNaturalTactica;
	}

	@Column(name = "HAB_NATURAL_MEDICINA")
	public Integer getHabNaturalMedicina() {
		return this.habNaturalMedicina;
	}

	public void setHabNaturalMedicina(Integer habNaturalMedicina) {
		this.habNaturalMedicina = habNaturalMedicina;
	}

	@Column(name = "HAB_NATURAL_MEMORIZAR")
	public Integer getHabNaturalMemorizar() {
		return this.habNaturalMemorizar;
	}

	public void setHabNaturalMemorizar(Integer habNaturalMemorizar) {
		this.habNaturalMemorizar = habNaturalMemorizar;
	}

	@Column(name = "HAB_NATURAL_NAVEGACION")
	public Integer getHabNaturalNavegacion() {
		return this.habNaturalNavegacion;
	}

	public void setHabNaturalNavegacion(Integer habNaturalNavegacion) {
		this.habNaturalNavegacion = habNaturalNavegacion;
	}

	@Column(name = "HAB_NATURAL_OCULTISMO")
	public Integer getHabNaturalOcultismo() {
		return this.habNaturalOcultismo;
	}

	public void setHabNaturalOcultismo(Integer habNaturalOcultismo) {
		this.habNaturalOcultismo = habNaturalOcultismo;
	}

	@Column(name = "HAB_NATURAL_TASACION")
	public Integer getHabNaturalTasacion() {
		return this.habNaturalTasacion;
	}

	public void setHabNaturalTasacion(Integer habNaturalTasacion) {
		this.habNaturalTasacion = habNaturalTasacion;
	}

	@Column(name = "HAB_NATURAL_VALORACION_MAGICA")
	public Integer getHabNaturalValoracionMagica() {
		return this.habNaturalValoracionMagica;
	}

	public void setHabNaturalValoracionMagica(Integer habNaturalValoracionMagica) {
		this.habNaturalValoracionMagica = habNaturalValoracionMagica;
	}

	@Column(name = "BONO_NOVEL_ANIMALES")
	public Integer getBonoNovelAnimales() {
		return this.bonoNovelAnimales;
	}

	public void setBonoNovelAnimales(Integer bonoNovelAnimales) {
		this.bonoNovelAnimales = bonoNovelAnimales;
	}

	@Column(name = "BONO_NOVEL_CIENCIA")
	public Integer getBonoNovelCiencia() {
		return this.bonoNovelCiencia;
	}

	public void setBonoNovelCiencia(Integer bonoNovelCiencia) {
		this.bonoNovelCiencia = bonoNovelCiencia;
	}

	@Column(name = "BONO_NOVEL_LEY")
	public Integer getBonoNovelLey() {
		return this.bonoNovelLey;
	}

	public void setBonoNovelLey(Integer bonoNovelLey) {
		this.bonoNovelLey = bonoNovelLey;
	}

	@Column(name = "BONO_NOVEL_HERBOLARIA")
	public Integer getBonoNovelHerbolaria() {
		return this.bonoNovelHerbolaria;
	}

	public void setBonoNovelHerbolaria(Integer bonoNovelHerbolaria) {
		this.bonoNovelHerbolaria = bonoNovelHerbolaria;
	}

	@Column(name = "BONO_NOVEL_HISTORIA")
	public Integer getBonoNovelHistoria() {
		return this.bonoNovelHistoria;
	}

	public void setBonoNovelHistoria(Integer bonoNovelHistoria) {
		this.bonoNovelHistoria = bonoNovelHistoria;
	}

	@Column(name = "BONO_NOVEL_TACTICA")
	public Integer getBonoNovelTactica() {
		return this.bonoNovelTactica;
	}

	public void setBonoNovelTactica(Integer bonoNovelTactica) {
		this.bonoNovelTactica = bonoNovelTactica;
	}

	@Column(name = "BONO_NOVEL_MEDICINA")
	public Integer getBonoNovelMedicina() {
		return this.bonoNovelMedicina;
	}

	public void setBonoNovelMedicina(Integer bonoNovelMedicina) {
		this.bonoNovelMedicina = bonoNovelMedicina;
	}

	@Column(name = "BONO_NOVEL_MEMORIZAR")
	public Integer getBonoNovelMemorizar() {
		return this.bonoNovelMemorizar;
	}

	public void setBonoNovelMemorizar(Integer bonoNovelMemorizar) {
		this.bonoNovelMemorizar = bonoNovelMemorizar;
	}

	@Column(name = "BONO_NOVEL_NAVEGACION")
	public Integer getBonoNovelNavegacion() {
		return this.bonoNovelNavegacion;
	}

	public void setBonoNovelNavegacion(Integer bonoNovelNavegacion) {
		this.bonoNovelNavegacion = bonoNovelNavegacion;
	}

	@Column(name = "BONO_NOVEL_OCULTISMO")
	public Integer getBonoNovelOcultismo() {
		return this.bonoNovelOcultismo;
	}

	public void setBonoNovelOcultismo(Integer bonoNovelOcultismo) {
		this.bonoNovelOcultismo = bonoNovelOcultismo;
	}

	@Column(name = "BONO_NOVEL_TASACION")
	public Integer getBonoNovelTasacion() {
		return this.bonoNovelTasacion;
	}

	public void setBonoNovelTasacion(Integer bonoNovelTasacion) {
		this.bonoNovelTasacion = bonoNovelTasacion;
	}

	@Column(name = "BONO_NOVEL_VALORACION_MAGICA")
	public Integer getBonoNovelValoracionMagica() {
		return this.bonoNovelValoracionMagica;
	}

	public void setBonoNovelValoracionMagica(Integer bonoNovelValoracionMagica) {
		this.bonoNovelValoracionMagica = bonoNovelValoracionMagica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdsSecundariasIntelectuales")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
