package modelo;
// Generated 24 may. 2021 13:40:54 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PdsSecundariasSubterfugio generated by hbm2java
 */
@Entity
@Table(name = "pds_secundarias_subterfugio", catalog = "anima_sheets_data")
public class PdsSecundariasSubterfugio implements java.io.Serializable {

	private int pdsSecundariasSubterfugio;
	private Integer pdsCerrajeria;
	private Integer pdsDisfraz;
	private Integer pdsOcultarse;
	private Integer pdsRobo;
	private Integer pdsSigilo;
	private Integer pdsTramperia;
	private Integer pdsVenenos;
	private Integer pdsEspCerrajeria;
	private Integer pdsEspDisfraz;
	private Integer pdsEspOcultarse;
	private Integer pdsEspRobo;
	private Integer pdsEspSigilo;
	private Integer pdsEspTramperia;
	private Integer pdsEspVenenos;
	private Integer bonoNaturalCerrajeria;
	private Integer bonoNaturalDisfraz;
	private Integer bonoNaturalOcultarse;
	private Integer bonoNaturalRobo;
	private Integer bonoNaturalSigilo;
	private Integer bonoNaturalTramperia;
	private Integer bonoNaturalVenenos;
	private Integer habNaturalCerrajeria;
	private Integer habNaturalDisfraz;
	private Integer habNaturalOcultarse;
	private Integer habNaturalRobo;
	private Integer habNaturalSigilo;
	private Integer habNaturalTramperia;
	private Integer habNaturalVenenos;
	private Integer bonoNovelCerrajeria;
	private Integer bonoNovelDisfraz;
	private Integer bonoNovelOcultarse;
	private Integer bonoNovelRobo;
	private Integer bonoNovelSigilo;
	private Integer bonoNovelTramperia;
	private Integer bonoNovelVenenos;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public PdsSecundariasSubterfugio() {
	}

	public PdsSecundariasSubterfugio(int pdsSecundariasSubterfugio) {
		this.pdsSecundariasSubterfugio = pdsSecundariasSubterfugio;
	}

	public PdsSecundariasSubterfugio(int pdsSecundariasSubterfugio, Integer pdsCerrajeria, Integer pdsDisfraz,
			Integer pdsOcultarse, Integer pdsRobo, Integer pdsSigilo, Integer pdsTramperia, Integer pdsVenenos,
			Integer pdsEspCerrajeria, Integer pdsEspDisfraz, Integer pdsEspOcultarse, Integer pdsEspRobo,
			Integer pdsEspSigilo, Integer pdsEspTramperia, Integer pdsEspVenenos, Integer bonoNaturalCerrajeria,
			Integer bonoNaturalDisfraz, Integer bonoNaturalOcultarse, Integer bonoNaturalRobo,
			Integer bonoNaturalSigilo, Integer bonoNaturalTramperia, Integer bonoNaturalVenenos,
			Integer habNaturalCerrajeria, Integer habNaturalDisfraz, Integer habNaturalOcultarse,
			Integer habNaturalRobo, Integer habNaturalSigilo, Integer habNaturalTramperia, Integer habNaturalVenenos,
			Integer bonoNovelCerrajeria, Integer bonoNovelDisfraz, Integer bonoNovelOcultarse, Integer bonoNovelRobo,
			Integer bonoNovelSigilo, Integer bonoNovelTramperia, Integer bonoNovelVenenos,
			Set<PdsCategoria> pdsCategorias) {
		this.pdsSecundariasSubterfugio = pdsSecundariasSubterfugio;
		this.pdsCerrajeria = pdsCerrajeria;
		this.pdsDisfraz = pdsDisfraz;
		this.pdsOcultarse = pdsOcultarse;
		this.pdsRobo = pdsRobo;
		this.pdsSigilo = pdsSigilo;
		this.pdsTramperia = pdsTramperia;
		this.pdsVenenos = pdsVenenos;
		this.pdsEspCerrajeria = pdsEspCerrajeria;
		this.pdsEspDisfraz = pdsEspDisfraz;
		this.pdsEspOcultarse = pdsEspOcultarse;
		this.pdsEspRobo = pdsEspRobo;
		this.pdsEspSigilo = pdsEspSigilo;
		this.pdsEspTramperia = pdsEspTramperia;
		this.pdsEspVenenos = pdsEspVenenos;
		this.bonoNaturalCerrajeria = bonoNaturalCerrajeria;
		this.bonoNaturalDisfraz = bonoNaturalDisfraz;
		this.bonoNaturalOcultarse = bonoNaturalOcultarse;
		this.bonoNaturalRobo = bonoNaturalRobo;
		this.bonoNaturalSigilo = bonoNaturalSigilo;
		this.bonoNaturalTramperia = bonoNaturalTramperia;
		this.bonoNaturalVenenos = bonoNaturalVenenos;
		this.habNaturalCerrajeria = habNaturalCerrajeria;
		this.habNaturalDisfraz = habNaturalDisfraz;
		this.habNaturalOcultarse = habNaturalOcultarse;
		this.habNaturalRobo = habNaturalRobo;
		this.habNaturalSigilo = habNaturalSigilo;
		this.habNaturalTramperia = habNaturalTramperia;
		this.habNaturalVenenos = habNaturalVenenos;
		this.bonoNovelCerrajeria = bonoNovelCerrajeria;
		this.bonoNovelDisfraz = bonoNovelDisfraz;
		this.bonoNovelOcultarse = bonoNovelOcultarse;
		this.bonoNovelRobo = bonoNovelRobo;
		this.bonoNovelSigilo = bonoNovelSigilo;
		this.bonoNovelTramperia = bonoNovelTramperia;
		this.bonoNovelVenenos = bonoNovelVenenos;
		this.pdsCategorias = pdsCategorias;
	}

	@Id

	@Column(name = "PDS_SECUNDARIAS_SUBTERFUGIO", unique = true, nullable = false)
	public int getPdsSecundariasSubterfugio() {
		return this.pdsSecundariasSubterfugio;
	}

	public void setPdsSecundariasSubterfugio(int pdsSecundariasSubterfugio) {
		this.pdsSecundariasSubterfugio = pdsSecundariasSubterfugio;
	}

	@Column(name = "PDS_CERRAJERIA")
	public Integer getPdsCerrajeria() {
		return this.pdsCerrajeria;
	}

	public void setPdsCerrajeria(Integer pdsCerrajeria) {
		this.pdsCerrajeria = pdsCerrajeria;
	}

	@Column(name = "PDS_DISFRAZ")
	public Integer getPdsDisfraz() {
		return this.pdsDisfraz;
	}

	public void setPdsDisfraz(Integer pdsDisfraz) {
		this.pdsDisfraz = pdsDisfraz;
	}

	@Column(name = "PDS_OCULTARSE")
	public Integer getPdsOcultarse() {
		return this.pdsOcultarse;
	}

	public void setPdsOcultarse(Integer pdsOcultarse) {
		this.pdsOcultarse = pdsOcultarse;
	}

	@Column(name = "PDS_ROBO")
	public Integer getPdsRobo() {
		return this.pdsRobo;
	}

	public void setPdsRobo(Integer pdsRobo) {
		this.pdsRobo = pdsRobo;
	}

	@Column(name = "PDS_SIGILO")
	public Integer getPdsSigilo() {
		return this.pdsSigilo;
	}

	public void setPdsSigilo(Integer pdsSigilo) {
		this.pdsSigilo = pdsSigilo;
	}

	@Column(name = "PDS_TRAMPERIA")
	public Integer getPdsTramperia() {
		return this.pdsTramperia;
	}

	public void setPdsTramperia(Integer pdsTramperia) {
		this.pdsTramperia = pdsTramperia;
	}

	@Column(name = "PDS_VENENOS")
	public Integer getPdsVenenos() {
		return this.pdsVenenos;
	}

	public void setPdsVenenos(Integer pdsVenenos) {
		this.pdsVenenos = pdsVenenos;
	}

	@Column(name = "PDS_ESP_CERRAJERIA")
	public Integer getPdsEspCerrajeria() {
		return this.pdsEspCerrajeria;
	}

	public void setPdsEspCerrajeria(Integer pdsEspCerrajeria) {
		this.pdsEspCerrajeria = pdsEspCerrajeria;
	}

	@Column(name = "PDS_ESP_DISFRAZ")
	public Integer getPdsEspDisfraz() {
		return this.pdsEspDisfraz;
	}

	public void setPdsEspDisfraz(Integer pdsEspDisfraz) {
		this.pdsEspDisfraz = pdsEspDisfraz;
	}

	@Column(name = "PDS_ESP_OCULTARSE")
	public Integer getPdsEspOcultarse() {
		return this.pdsEspOcultarse;
	}

	public void setPdsEspOcultarse(Integer pdsEspOcultarse) {
		this.pdsEspOcultarse = pdsEspOcultarse;
	}

	@Column(name = "PDS_ESP_ROBO")
	public Integer getPdsEspRobo() {
		return this.pdsEspRobo;
	}

	public void setPdsEspRobo(Integer pdsEspRobo) {
		this.pdsEspRobo = pdsEspRobo;
	}

	@Column(name = "PDS_ESP_SIGILO")
	public Integer getPdsEspSigilo() {
		return this.pdsEspSigilo;
	}

	public void setPdsEspSigilo(Integer pdsEspSigilo) {
		this.pdsEspSigilo = pdsEspSigilo;
	}

	@Column(name = "PDS_ESP_TRAMPERIA")
	public Integer getPdsEspTramperia() {
		return this.pdsEspTramperia;
	}

	public void setPdsEspTramperia(Integer pdsEspTramperia) {
		this.pdsEspTramperia = pdsEspTramperia;
	}

	@Column(name = "PDS_ESP_VENENOS")
	public Integer getPdsEspVenenos() {
		return this.pdsEspVenenos;
	}

	public void setPdsEspVenenos(Integer pdsEspVenenos) {
		this.pdsEspVenenos = pdsEspVenenos;
	}

	@Column(name = "BONO_NATURAL_CERRAJERIA")
	public Integer getBonoNaturalCerrajeria() {
		return this.bonoNaturalCerrajeria;
	}

	public void setBonoNaturalCerrajeria(Integer bonoNaturalCerrajeria) {
		this.bonoNaturalCerrajeria = bonoNaturalCerrajeria;
	}

	@Column(name = "BONO_NATURAL_DISFRAZ")
	public Integer getBonoNaturalDisfraz() {
		return this.bonoNaturalDisfraz;
	}

	public void setBonoNaturalDisfraz(Integer bonoNaturalDisfraz) {
		this.bonoNaturalDisfraz = bonoNaturalDisfraz;
	}

	@Column(name = "BONO_NATURAL_OCULTARSE")
	public Integer getBonoNaturalOcultarse() {
		return this.bonoNaturalOcultarse;
	}

	public void setBonoNaturalOcultarse(Integer bonoNaturalOcultarse) {
		this.bonoNaturalOcultarse = bonoNaturalOcultarse;
	}

	@Column(name = "BONO_NATURAL_ROBO")
	public Integer getBonoNaturalRobo() {
		return this.bonoNaturalRobo;
	}

	public void setBonoNaturalRobo(Integer bonoNaturalRobo) {
		this.bonoNaturalRobo = bonoNaturalRobo;
	}

	@Column(name = "BONO_NATURAL_SIGILO")
	public Integer getBonoNaturalSigilo() {
		return this.bonoNaturalSigilo;
	}

	public void setBonoNaturalSigilo(Integer bonoNaturalSigilo) {
		this.bonoNaturalSigilo = bonoNaturalSigilo;
	}

	@Column(name = "BONO_NATURAL_TRAMPERIA")
	public Integer getBonoNaturalTramperia() {
		return this.bonoNaturalTramperia;
	}

	public void setBonoNaturalTramperia(Integer bonoNaturalTramperia) {
		this.bonoNaturalTramperia = bonoNaturalTramperia;
	}

	@Column(name = "BONO_NATURAL_VENENOS")
	public Integer getBonoNaturalVenenos() {
		return this.bonoNaturalVenenos;
	}

	public void setBonoNaturalVenenos(Integer bonoNaturalVenenos) {
		this.bonoNaturalVenenos = bonoNaturalVenenos;
	}

	@Column(name = "HAB_NATURAL_CERRAJERIA")
	public Integer getHabNaturalCerrajeria() {
		return this.habNaturalCerrajeria;
	}

	public void setHabNaturalCerrajeria(Integer habNaturalCerrajeria) {
		this.habNaturalCerrajeria = habNaturalCerrajeria;
	}

	@Column(name = "HAB_NATURAL_DISFRAZ")
	public Integer getHabNaturalDisfraz() {
		return this.habNaturalDisfraz;
	}

	public void setHabNaturalDisfraz(Integer habNaturalDisfraz) {
		this.habNaturalDisfraz = habNaturalDisfraz;
	}

	@Column(name = "HAB_NATURAL_OCULTARSE")
	public Integer getHabNaturalOcultarse() {
		return this.habNaturalOcultarse;
	}

	public void setHabNaturalOcultarse(Integer habNaturalOcultarse) {
		this.habNaturalOcultarse = habNaturalOcultarse;
	}

	@Column(name = "HAB_NATURAL_ROBO")
	public Integer getHabNaturalRobo() {
		return this.habNaturalRobo;
	}

	public void setHabNaturalRobo(Integer habNaturalRobo) {
		this.habNaturalRobo = habNaturalRobo;
	}

	@Column(name = "HAB_NATURAL_SIGILO")
	public Integer getHabNaturalSigilo() {
		return this.habNaturalSigilo;
	}

	public void setHabNaturalSigilo(Integer habNaturalSigilo) {
		this.habNaturalSigilo = habNaturalSigilo;
	}

	@Column(name = "HAB_NATURAL_TRAMPERIA")
	public Integer getHabNaturalTramperia() {
		return this.habNaturalTramperia;
	}

	public void setHabNaturalTramperia(Integer habNaturalTramperia) {
		this.habNaturalTramperia = habNaturalTramperia;
	}

	@Column(name = "HAB_NATURAL_VENENOS")
	public Integer getHabNaturalVenenos() {
		return this.habNaturalVenenos;
	}

	public void setHabNaturalVenenos(Integer habNaturalVenenos) {
		this.habNaturalVenenos = habNaturalVenenos;
	}

	@Column(name = "BONO_NOVEL_CERRAJERIA")
	public Integer getBonoNovelCerrajeria() {
		return this.bonoNovelCerrajeria;
	}

	public void setBonoNovelCerrajeria(Integer bonoNovelCerrajeria) {
		this.bonoNovelCerrajeria = bonoNovelCerrajeria;
	}

	@Column(name = "BONO_NOVEL_DISFRAZ")
	public Integer getBonoNovelDisfraz() {
		return this.bonoNovelDisfraz;
	}

	public void setBonoNovelDisfraz(Integer bonoNovelDisfraz) {
		this.bonoNovelDisfraz = bonoNovelDisfraz;
	}

	@Column(name = "BONO_NOVEL_OCULTARSE")
	public Integer getBonoNovelOcultarse() {
		return this.bonoNovelOcultarse;
	}

	public void setBonoNovelOcultarse(Integer bonoNovelOcultarse) {
		this.bonoNovelOcultarse = bonoNovelOcultarse;
	}

	@Column(name = "BONO_NOVEL_ROBO")
	public Integer getBonoNovelRobo() {
		return this.bonoNovelRobo;
	}

	public void setBonoNovelRobo(Integer bonoNovelRobo) {
		this.bonoNovelRobo = bonoNovelRobo;
	}

	@Column(name = "BONO_NOVEL_SIGILO")
	public Integer getBonoNovelSigilo() {
		return this.bonoNovelSigilo;
	}

	public void setBonoNovelSigilo(Integer bonoNovelSigilo) {
		this.bonoNovelSigilo = bonoNovelSigilo;
	}

	@Column(name = "BONO_NOVEL_TRAMPERIA")
	public Integer getBonoNovelTramperia() {
		return this.bonoNovelTramperia;
	}

	public void setBonoNovelTramperia(Integer bonoNovelTramperia) {
		this.bonoNovelTramperia = bonoNovelTramperia;
	}

	@Column(name = "BONO_NOVEL_VENENOS")
	public Integer getBonoNovelVenenos() {
		return this.bonoNovelVenenos;
	}

	public void setBonoNovelVenenos(Integer bonoNovelVenenos) {
		this.bonoNovelVenenos = bonoNovelVenenos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdsSecundariasSubterfugio")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
