package modelo;
// Generated 11 jun. 2021 0:33:09 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PdsSecundariasSociales generated by hbm2java
 */
@Entity
@Table(name = "pds_secundarias_sociales", catalog = "anima_sheets_data")
public class PdsSecundariasSociales implements java.io.Serializable {

	private int pdsSecundariasSociales;
	private Integer pdsAcrobacias;
	private Integer pdsAtletismo;
	private Integer pdsMontar;
	private Integer pdsNadar;
	private Integer pdsTrepar;
	private Integer pdsSaltar;
	private Integer pdsPilotar;
	private Integer pdsEspEstilo;
	private Integer pdsEspIntimidar;
	private Integer pdsEspLiderazgo;
	private Integer pdsEspPersuasion;
	private Integer pdsEspComercio;
	private Integer pdsEspCallejeo;
	private Integer pdsEspEtiqueta;
	private Integer bonoNaturalEstilo;
	private Integer bonoNaturalIntimidar;
	private Integer bonoNaturalLiderazgo;
	private Integer bonoNaturalPersuasion;
	private Integer bonoNaturalComercio;
	private Integer bonoNaturalCallejeo;
	private Integer bonoNaturalEtiqueta;
	private Integer habNaturalEstilo;
	private Integer habNaturalIntimidar;
	private Integer habNaturalLiderazgo;
	private Integer habNaturalPersuasion;
	private Integer habNaturalComercio;
	private Integer habNaturalCallejeo;
	private Integer habNaturalEtiqueta;
	private Integer bonoNovelEstilo;
	private Integer bonoNovelIntimidar;
	private Integer bonoNovelLiderazgo;
	private Integer bonoNovelPersuasion;
	private Integer bonoNovelComercio;
	private Integer bonoNovelCallejeo;
	private Integer bonoNovelEtiqueta;
	private Set<PdsCategoria> pdsCategorias = new HashSet<PdsCategoria>(0);

	public PdsSecundariasSociales() {
	}

	public PdsSecundariasSociales(int pdsSecundariasSociales) {
		this.pdsSecundariasSociales = pdsSecundariasSociales;
	}

	public PdsSecundariasSociales(int pdsSecundariasSociales, Integer pdsAcrobacias, Integer pdsAtletismo,
			Integer pdsMontar, Integer pdsNadar, Integer pdsTrepar, Integer pdsSaltar, Integer pdsPilotar,
			Integer pdsEspEstilo, Integer pdsEspIntimidar, Integer pdsEspLiderazgo, Integer pdsEspPersuasion,
			Integer pdsEspComercio, Integer pdsEspCallejeo, Integer pdsEspEtiqueta, Integer bonoNaturalEstilo,
			Integer bonoNaturalIntimidar, Integer bonoNaturalLiderazgo, Integer bonoNaturalPersuasion,
			Integer bonoNaturalComercio, Integer bonoNaturalCallejeo, Integer bonoNaturalEtiqueta,
			Integer habNaturalEstilo, Integer habNaturalIntimidar, Integer habNaturalLiderazgo,
			Integer habNaturalPersuasion, Integer habNaturalComercio, Integer habNaturalCallejeo,
			Integer habNaturalEtiqueta, Integer bonoNovelEstilo, Integer bonoNovelIntimidar, Integer bonoNovelLiderazgo,
			Integer bonoNovelPersuasion, Integer bonoNovelComercio, Integer bonoNovelCallejeo,
			Integer bonoNovelEtiqueta, Set<PdsCategoria> pdsCategorias) {
		this.pdsSecundariasSociales = pdsSecundariasSociales;
		this.pdsAcrobacias = pdsAcrobacias;
		this.pdsAtletismo = pdsAtletismo;
		this.pdsMontar = pdsMontar;
		this.pdsNadar = pdsNadar;
		this.pdsTrepar = pdsTrepar;
		this.pdsSaltar = pdsSaltar;
		this.pdsPilotar = pdsPilotar;
		this.pdsEspEstilo = pdsEspEstilo;
		this.pdsEspIntimidar = pdsEspIntimidar;
		this.pdsEspLiderazgo = pdsEspLiderazgo;
		this.pdsEspPersuasion = pdsEspPersuasion;
		this.pdsEspComercio = pdsEspComercio;
		this.pdsEspCallejeo = pdsEspCallejeo;
		this.pdsEspEtiqueta = pdsEspEtiqueta;
		this.bonoNaturalEstilo = bonoNaturalEstilo;
		this.bonoNaturalIntimidar = bonoNaturalIntimidar;
		this.bonoNaturalLiderazgo = bonoNaturalLiderazgo;
		this.bonoNaturalPersuasion = bonoNaturalPersuasion;
		this.bonoNaturalComercio = bonoNaturalComercio;
		this.bonoNaturalCallejeo = bonoNaturalCallejeo;
		this.bonoNaturalEtiqueta = bonoNaturalEtiqueta;
		this.habNaturalEstilo = habNaturalEstilo;
		this.habNaturalIntimidar = habNaturalIntimidar;
		this.habNaturalLiderazgo = habNaturalLiderazgo;
		this.habNaturalPersuasion = habNaturalPersuasion;
		this.habNaturalComercio = habNaturalComercio;
		this.habNaturalCallejeo = habNaturalCallejeo;
		this.habNaturalEtiqueta = habNaturalEtiqueta;
		this.bonoNovelEstilo = bonoNovelEstilo;
		this.bonoNovelIntimidar = bonoNovelIntimidar;
		this.bonoNovelLiderazgo = bonoNovelLiderazgo;
		this.bonoNovelPersuasion = bonoNovelPersuasion;
		this.bonoNovelComercio = bonoNovelComercio;
		this.bonoNovelCallejeo = bonoNovelCallejeo;
		this.bonoNovelEtiqueta = bonoNovelEtiqueta;
		this.pdsCategorias = pdsCategorias;
	}

	@Id

	@Column(name = "PDS_SECUNDARIAS_SOCIALES", unique = true, nullable = false)
	public int getPdsSecundariasSociales() {
		return this.pdsSecundariasSociales;
	}

	public void setPdsSecundariasSociales(int pdsSecundariasSociales) {
		this.pdsSecundariasSociales = pdsSecundariasSociales;
	}

	@Column(name = "PDS_ACROBACIAS")
	public Integer getPdsAcrobacias() {
		return this.pdsAcrobacias;
	}

	public void setPdsAcrobacias(Integer pdsAcrobacias) {
		this.pdsAcrobacias = pdsAcrobacias;
	}

	@Column(name = "PDS_ATLETISMO")
	public Integer getPdsAtletismo() {
		return this.pdsAtletismo;
	}

	public void setPdsAtletismo(Integer pdsAtletismo) {
		this.pdsAtletismo = pdsAtletismo;
	}

	@Column(name = "PDS_MONTAR")
	public Integer getPdsMontar() {
		return this.pdsMontar;
	}

	public void setPdsMontar(Integer pdsMontar) {
		this.pdsMontar = pdsMontar;
	}

	@Column(name = "PDS_NADAR")
	public Integer getPdsNadar() {
		return this.pdsNadar;
	}

	public void setPdsNadar(Integer pdsNadar) {
		this.pdsNadar = pdsNadar;
	}

	@Column(name = "PDS_TREPAR")
	public Integer getPdsTrepar() {
		return this.pdsTrepar;
	}

	public void setPdsTrepar(Integer pdsTrepar) {
		this.pdsTrepar = pdsTrepar;
	}

	@Column(name = "PDS_SALTAR")
	public Integer getPdsSaltar() {
		return this.pdsSaltar;
	}

	public void setPdsSaltar(Integer pdsSaltar) {
		this.pdsSaltar = pdsSaltar;
	}

	@Column(name = "PDS_PILOTAR")
	public Integer getPdsPilotar() {
		return this.pdsPilotar;
	}

	public void setPdsPilotar(Integer pdsPilotar) {
		this.pdsPilotar = pdsPilotar;
	}

	@Column(name = "PDS_ESP_ESTILO")
	public Integer getPdsEspEstilo() {
		return this.pdsEspEstilo;
	}

	public void setPdsEspEstilo(Integer pdsEspEstilo) {
		this.pdsEspEstilo = pdsEspEstilo;
	}

	@Column(name = "PDS_ESP_INTIMIDAR")
	public Integer getPdsEspIntimidar() {
		return this.pdsEspIntimidar;
	}

	public void setPdsEspIntimidar(Integer pdsEspIntimidar) {
		this.pdsEspIntimidar = pdsEspIntimidar;
	}

	@Column(name = "PDS_ESP_LIDERAZGO")
	public Integer getPdsEspLiderazgo() {
		return this.pdsEspLiderazgo;
	}

	public void setPdsEspLiderazgo(Integer pdsEspLiderazgo) {
		this.pdsEspLiderazgo = pdsEspLiderazgo;
	}

	@Column(name = "PDS_ESP_PERSUASION")
	public Integer getPdsEspPersuasion() {
		return this.pdsEspPersuasion;
	}

	public void setPdsEspPersuasion(Integer pdsEspPersuasion) {
		this.pdsEspPersuasion = pdsEspPersuasion;
	}

	@Column(name = "PDS_ESP_COMERCIO")
	public Integer getPdsEspComercio() {
		return this.pdsEspComercio;
	}

	public void setPdsEspComercio(Integer pdsEspComercio) {
		this.pdsEspComercio = pdsEspComercio;
	}

	@Column(name = "PDS_ESP_CALLEJEO")
	public Integer getPdsEspCallejeo() {
		return this.pdsEspCallejeo;
	}

	public void setPdsEspCallejeo(Integer pdsEspCallejeo) {
		this.pdsEspCallejeo = pdsEspCallejeo;
	}

	@Column(name = "PDS_ESP_ETIQUETA")
	public Integer getPdsEspEtiqueta() {
		return this.pdsEspEtiqueta;
	}

	public void setPdsEspEtiqueta(Integer pdsEspEtiqueta) {
		this.pdsEspEtiqueta = pdsEspEtiqueta;
	}

	@Column(name = "BONO_NATURAL_ESTILO")
	public Integer getBonoNaturalEstilo() {
		return this.bonoNaturalEstilo;
	}

	public void setBonoNaturalEstilo(Integer bonoNaturalEstilo) {
		this.bonoNaturalEstilo = bonoNaturalEstilo;
	}

	@Column(name = "BONO_NATURAL_INTIMIDAR")
	public Integer getBonoNaturalIntimidar() {
		return this.bonoNaturalIntimidar;
	}

	public void setBonoNaturalIntimidar(Integer bonoNaturalIntimidar) {
		this.bonoNaturalIntimidar = bonoNaturalIntimidar;
	}

	@Column(name = "BONO_NATURAL_LIDERAZGO")
	public Integer getBonoNaturalLiderazgo() {
		return this.bonoNaturalLiderazgo;
	}

	public void setBonoNaturalLiderazgo(Integer bonoNaturalLiderazgo) {
		this.bonoNaturalLiderazgo = bonoNaturalLiderazgo;
	}

	@Column(name = "BONO_NATURAL_PERSUASION")
	public Integer getBonoNaturalPersuasion() {
		return this.bonoNaturalPersuasion;
	}

	public void setBonoNaturalPersuasion(Integer bonoNaturalPersuasion) {
		this.bonoNaturalPersuasion = bonoNaturalPersuasion;
	}

	@Column(name = "BONO_NATURAL_COMERCIO")
	public Integer getBonoNaturalComercio() {
		return this.bonoNaturalComercio;
	}

	public void setBonoNaturalComercio(Integer bonoNaturalComercio) {
		this.bonoNaturalComercio = bonoNaturalComercio;
	}

	@Column(name = "BONO_NATURAL_CALLEJEO")
	public Integer getBonoNaturalCallejeo() {
		return this.bonoNaturalCallejeo;
	}

	public void setBonoNaturalCallejeo(Integer bonoNaturalCallejeo) {
		this.bonoNaturalCallejeo = bonoNaturalCallejeo;
	}

	@Column(name = "BONO_NATURAL_ETIQUETA")
	public Integer getBonoNaturalEtiqueta() {
		return this.bonoNaturalEtiqueta;
	}

	public void setBonoNaturalEtiqueta(Integer bonoNaturalEtiqueta) {
		this.bonoNaturalEtiqueta = bonoNaturalEtiqueta;
	}

	@Column(name = "HAB_NATURAL_ESTILO")
	public Integer getHabNaturalEstilo() {
		return this.habNaturalEstilo;
	}

	public void setHabNaturalEstilo(Integer habNaturalEstilo) {
		this.habNaturalEstilo = habNaturalEstilo;
	}

	@Column(name = "HAB_NATURAL_INTIMIDAR")
	public Integer getHabNaturalIntimidar() {
		return this.habNaturalIntimidar;
	}

	public void setHabNaturalIntimidar(Integer habNaturalIntimidar) {
		this.habNaturalIntimidar = habNaturalIntimidar;
	}

	@Column(name = "HAB_NATURAL_LIDERAZGO")
	public Integer getHabNaturalLiderazgo() {
		return this.habNaturalLiderazgo;
	}

	public void setHabNaturalLiderazgo(Integer habNaturalLiderazgo) {
		this.habNaturalLiderazgo = habNaturalLiderazgo;
	}

	@Column(name = "HAB_NATURAL_PERSUASION")
	public Integer getHabNaturalPersuasion() {
		return this.habNaturalPersuasion;
	}

	public void setHabNaturalPersuasion(Integer habNaturalPersuasion) {
		this.habNaturalPersuasion = habNaturalPersuasion;
	}

	@Column(name = "HAB_NATURAL_COMERCIO")
	public Integer getHabNaturalComercio() {
		return this.habNaturalComercio;
	}

	public void setHabNaturalComercio(Integer habNaturalComercio) {
		this.habNaturalComercio = habNaturalComercio;
	}

	@Column(name = "HAB_NATURAL_CALLEJEO")
	public Integer getHabNaturalCallejeo() {
		return this.habNaturalCallejeo;
	}

	public void setHabNaturalCallejeo(Integer habNaturalCallejeo) {
		this.habNaturalCallejeo = habNaturalCallejeo;
	}

	@Column(name = "HAB_NATURAL_ETIQUETA")
	public Integer getHabNaturalEtiqueta() {
		return this.habNaturalEtiqueta;
	}

	public void setHabNaturalEtiqueta(Integer habNaturalEtiqueta) {
		this.habNaturalEtiqueta = habNaturalEtiqueta;
	}

	@Column(name = "BONO_NOVEL_ESTILO")
	public Integer getBonoNovelEstilo() {
		return this.bonoNovelEstilo;
	}

	public void setBonoNovelEstilo(Integer bonoNovelEstilo) {
		this.bonoNovelEstilo = bonoNovelEstilo;
	}

	@Column(name = "BONO_NOVEL_INTIMIDAR")
	public Integer getBonoNovelIntimidar() {
		return this.bonoNovelIntimidar;
	}

	public void setBonoNovelIntimidar(Integer bonoNovelIntimidar) {
		this.bonoNovelIntimidar = bonoNovelIntimidar;
	}

	@Column(name = "BONO_NOVEL_LIDERAZGO")
	public Integer getBonoNovelLiderazgo() {
		return this.bonoNovelLiderazgo;
	}

	public void setBonoNovelLiderazgo(Integer bonoNovelLiderazgo) {
		this.bonoNovelLiderazgo = bonoNovelLiderazgo;
	}

	@Column(name = "BONO_NOVEL_PERSUASION")
	public Integer getBonoNovelPersuasion() {
		return this.bonoNovelPersuasion;
	}

	public void setBonoNovelPersuasion(Integer bonoNovelPersuasion) {
		this.bonoNovelPersuasion = bonoNovelPersuasion;
	}

	@Column(name = "BONO_NOVEL_COMERCIO")
	public Integer getBonoNovelComercio() {
		return this.bonoNovelComercio;
	}

	public void setBonoNovelComercio(Integer bonoNovelComercio) {
		this.bonoNovelComercio = bonoNovelComercio;
	}

	@Column(name = "BONO_NOVEL_CALLEJEO")
	public Integer getBonoNovelCallejeo() {
		return this.bonoNovelCallejeo;
	}

	public void setBonoNovelCallejeo(Integer bonoNovelCallejeo) {
		this.bonoNovelCallejeo = bonoNovelCallejeo;
	}

	@Column(name = "BONO_NOVEL_ETIQUETA")
	public Integer getBonoNovelEtiqueta() {
		return this.bonoNovelEtiqueta;
	}

	public void setBonoNovelEtiqueta(Integer bonoNovelEtiqueta) {
		this.bonoNovelEtiqueta = bonoNovelEtiqueta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdsSecundariasSociales")
	public Set<PdsCategoria> getPdsCategorias() {
		return this.pdsCategorias;
	}

	public void setPdsCategorias(Set<PdsCategoria> pdsCategorias) {
		this.pdsCategorias = pdsCategorias;
	}

}
