package modelo;
// Generated 12 jun. 2021 20:12:54 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Personaje generated by hbm2java
 */
@Entity
@Table(name = "personaje", catalog = "anima_sheets_data")
public class Personaje implements java.io.Serializable {

	private int idPersonaje;
	private Jugador jugador;
	private Raza raza;
	private String armaConocida;
	private String nombre;
	private Integer edad;
	private Integer apariencia;
	private String descripcion;
	private String particularidades;
	private String objetivos;
	private String historia;
	private Integer xp;
	private String origen;
	private String etnia;
	private String imagen;
	private Integer cansancioEspecial;
	private Integer pvEspecial;
	private Integer turnoEspecial;
	private Set<Armadura> armaduras = new HashSet<Armadura>(0);
	private Lv lv;
	private Set<ArmaPersonaje> armaPersonajes = new HashSet<ArmaPersonaje>(0);
	private Set<Desventaja> desventajas = new HashSet<Desventaja>(0);
	private Set<TablaPsiquico> tablaPsiquicos = new HashSet<TablaPsiquico>(0);
	private Set<TablaMagia> tablaMagias = new HashSet<TablaMagia>(0);
	private Set<ArteMarcial> arteMarcials = new HashSet<ArteMarcial>(0);
	private Caracteristicas caracteristicas;
	private Set<TablaArma> tablaArmas = new HashSet<TablaArma>(0);
	private Set<TablaEstilo> tablaEstilos = new HashSet<TablaEstilo>(0);
	private Set<TablaPatronMental> tablaPatronMentals = new HashSet<TablaPatronMental>(0);
	private Set<Idioma> idiomas = new HashSet<Idioma>(0);
	private Set<Ventaja> ventajas = new HashSet<Ventaja>(0);

	public Personaje() {
	}

	public Personaje(int idPersonaje, Jugador jugador, Raza raza, String nombre) {
		this.idPersonaje = idPersonaje;
		this.jugador = jugador;
		this.raza = raza;
		this.nombre = nombre;
	}

	public Personaje(int idPersonaje, Jugador jugador, Raza raza, String armaConocida, String nombre, Integer edad,
			Integer apariencia, String descripcion, String particularidades, String objetivos, String historia,
			Integer xp, String origen, String etnia, String imagen, Integer cansancioEspecial, Integer pvEspecial,
			Integer turnoEspecial, Set<Armadura> armaduras, Lv lv, Set<ArmaPersonaje> armaPersonajes,
			Set<Desventaja> desventajas, Set<TablaPsiquico> tablaPsiquicos, Set<TablaMagia> tablaMagias,
			Set<ArteMarcial> arteMarcials, Caracteristicas caracteristicas, Set<TablaArma> tablaArmas,
			Set<TablaEstilo> tablaEstilos, Set<TablaPatronMental> tablaPatronMentals, Set<Idioma> idiomas,
			Set<Ventaja> ventajas) {
		this.idPersonaje = idPersonaje;
		this.jugador = jugador;
		this.raza = raza;
		this.armaConocida = armaConocida;
		this.nombre = nombre;
		this.edad = edad;
		this.apariencia = apariencia;
		this.descripcion = descripcion;
		this.particularidades = particularidades;
		this.objetivos = objetivos;
		this.historia = historia;
		this.xp = xp;
		this.origen = origen;
		this.etnia = etnia;
		this.imagen = imagen;
		this.cansancioEspecial = cansancioEspecial;
		this.pvEspecial = pvEspecial;
		this.turnoEspecial = turnoEspecial;
		this.armaduras = armaduras;
		this.lv = lv;
		this.armaPersonajes = armaPersonajes;
		this.desventajas = desventajas;
		this.tablaPsiquicos = tablaPsiquicos;
		this.tablaMagias = tablaMagias;
		this.arteMarcials = arteMarcials;
		this.caracteristicas = caracteristicas;
		this.tablaArmas = tablaArmas;
		this.tablaEstilos = tablaEstilos;
		this.tablaPatronMentals = tablaPatronMentals;
		this.idiomas = idiomas;
		this.ventajas = ventajas;
	}

	@Id

	@Column(name = "ID_PERSONAJE", unique = true, nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JUGADOR", nullable = false)
	public Jugador getJugador() {
		return this.jugador;
	}

	public void setJugador(Jugador jugador) {
		this.jugador = jugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RAZA", nullable = false)
	public Raza getRaza() {
		return this.raza;
	}

	public void setRaza(Raza raza) {
		this.raza = raza;
	}

	@Column(name = "ARMA_CONOCIDA", length = 100)
	public String getArmaConocida() {
		return this.armaConocida;
	}

	public void setArmaConocida(String armaConocida) {
		this.armaConocida = armaConocida;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "EDAD")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "APARIENCIA")
	public Integer getApariencia() {
		return this.apariencia;
	}

	public void setApariencia(Integer apariencia) {
		this.apariencia = apariencia;
	}

	@Column(name = "DESCRIPCION", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "PARTICULARIDADES", length = 65535)
	public String getParticularidades() {
		return this.particularidades;
	}

	public void setParticularidades(String particularidades) {
		this.particularidades = particularidades;
	}

	@Column(name = "OBJETIVOS", length = 65535)
	public String getObjetivos() {
		return this.objetivos;
	}

	public void setObjetivos(String objetivos) {
		this.objetivos = objetivos;
	}

	@Column(name = "HISTORIA", length = 65535)
	public String getHistoria() {
		return this.historia;
	}

	public void setHistoria(String historia) {
		this.historia = historia;
	}

	@Column(name = "XP")
	public Integer getXp() {
		return this.xp;
	}

	public void setXp(Integer xp) {
		this.xp = xp;
	}

	@Column(name = "ORIGEN", length = 50)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "ETNIA", length = 50)
	public String getEtnia() {
		return this.etnia;
	}

	public void setEtnia(String etnia) {
		this.etnia = etnia;
	}

	@Column(name = "IMAGEN", length = 250)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "CANSANCIO_ESPECIAL")
	public Integer getCansancioEspecial() {
		return this.cansancioEspecial;
	}

	public void setCansancioEspecial(Integer cansancioEspecial) {
		this.cansancioEspecial = cansancioEspecial;
	}

	@Column(name = "PV_ESPECIAL")
	public Integer getPvEspecial() {
		return this.pvEspecial;
	}

	public void setPvEspecial(Integer pvEspecial) {
		this.pvEspecial = pvEspecial;
	}

	@Column(name = "TURNO_ESPECIAL")
	public Integer getTurnoEspecial() {
		return this.turnoEspecial;
	}

	public void setTurnoEspecial(Integer turnoEspecial) {
		this.turnoEspecial = turnoEspecial;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<Armadura> getArmaduras() {
		return this.armaduras;
	}

	public void setArmaduras(Set<Armadura> armaduras) {
		this.armaduras = armaduras;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personaje")
	public Lv getLv() {
		return this.lv;
	}

	public void setLv(Lv lv) {
		this.lv = lv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personaje")
	public Set<ArmaPersonaje> getArmaPersonajes() {
		return this.armaPersonajes;
	}

	public void setArmaPersonajes(Set<ArmaPersonaje> armaPersonajes) {
		this.armaPersonajes = armaPersonajes;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<Desventaja> getDesventajas() {
		return this.desventajas;
	}

	public void setDesventajas(Set<Desventaja> desventajas) {
		this.desventajas = desventajas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<TablaPsiquico> getTablaPsiquicos() {
		return this.tablaPsiquicos;
	}

	public void setTablaPsiquicos(Set<TablaPsiquico> tablaPsiquicos) {
		this.tablaPsiquicos = tablaPsiquicos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<TablaMagia> getTablaMagias() {
		return this.tablaMagias;
	}

	public void setTablaMagias(Set<TablaMagia> tablaMagias) {
		this.tablaMagias = tablaMagias;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<ArteMarcial> getArteMarcials() {
		return this.arteMarcials;
	}

	public void setArteMarcials(Set<ArteMarcial> arteMarcials) {
		this.arteMarcials = arteMarcials;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personaje")
	public Caracteristicas getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(Caracteristicas caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<TablaArma> getTablaArmas() {
		return this.tablaArmas;
	}

	public void setTablaArmas(Set<TablaArma> tablaArmas) {
		this.tablaArmas = tablaArmas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<TablaEstilo> getTablaEstilos() {
		return this.tablaEstilos;
	}

	public void setTablaEstilos(Set<TablaEstilo> tablaEstilos) {
		this.tablaEstilos = tablaEstilos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<TablaPatronMental> getTablaPatronMentals() {
		return this.tablaPatronMentals;
	}

	public void setTablaPatronMentals(Set<TablaPatronMental> tablaPatronMentals) {
		this.tablaPatronMentals = tablaPatronMentals;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<Idioma> getIdiomas() {
		return this.idiomas;
	}

	public void setIdiomas(Set<Idioma> idiomas) {
		this.idiomas = idiomas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<Ventaja> getVentajas() {
		return this.ventajas;
	}

	public void setVentajas(Set<Ventaja> ventajas) {
		this.ventajas = ventajas;
	}

}
