package modelo;
// Generated 16 jun. 2021 23:54:00 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Personaje generated by hbm2java
 */
@Entity
@Table(name = "personaje", catalog = "anima_sheets_data")
public class Personaje implements java.io.Serializable {

	private int idPersonaje;
	private Categoria categoria;
	private Raza raza;
	private String armaConocida;
	private String nombre;
	private Integer edad;
	private Integer apariencia;
	private Integer nivel;
	private String descripcion;
	private String particularidades;
	private String objetivos;
	private String historia;
	private String equipoCombate;
	private String vestimentaAccesorios;
	private String equipoVariado;
	private String contactos;
	private String titulosPosesiones;
	private String monedasOro;
	private String monedasPlata;
	private String monedasCobre;
	private String joyas;
	private String origen;
	private String etnia;
	private String imagen;
	private Integer cansancioEspecial;
	private Integer regeneracionEspecial;
	private Integer pvEspecial;
	private Integer turnoEspecial;
	private Integer cvInvertido;
	private PdsSecundariasSubterfugio pdsSecundariasSubterfugio;
	private PdsSecundariasPerceptivas pdsSecundariasPerceptivas;
	private PdsPrimariasKi pdsPrimariasKi;
	private PdsSecundariasCreativas pdsSecundariasCreativas;
	private PdsSecundariasVigor pdsSecundariasVigor;
	private Set<Armadura> armaduras = new HashSet<Armadura>(0);
	private Set<Arma> armas = new HashSet<Arma>(0);
	private Set<Desventaja> desventajas = new HashSet<Desventaja>(0);
	private Set<TablaPsiquico> tablaPsiquicos = new HashSet<TablaPsiquico>(0);
	private Set<TablaTablaViasMagiaPersonaje> tablaTablaViasMagiaPersonajes = new HashSet<TablaTablaViasMagiaPersonaje>(
			0);
	private PdsPrimariasPsiquicas pdsPrimariasPsiquicas;
	private PdsSecundariasAtleticas pdsSecundariasAtleticas;
	private PdsPrimariasMisticas pdsPrimariasMisticas;
	private PdsSecundariasSociales pdsSecundariasSociales;
	private Set<TablaMagia> tablaMagias = new HashSet<TablaMagia>(0);
	private Set<ArteMarcial> arteMarcials = new HashSet<ArteMarcial>(0);
	private Caracteristicas caracteristicas;
	private PdsPrimariasComunes pdsPrimariasComunes;
	private PdsSecundariasIntelectuales pdsSecundariasIntelectuales;
	private Set<TablaEstilo> tablaEstilos = new HashSet<TablaEstilo>(0);
	private Set<PoderPsiquico> poderPsiquicos = new HashSet<PoderPsiquico>(0);
	private Set<TablaConjurosLibreAcceso> tablaConjurosLibreAccesos = new HashSet<TablaConjurosLibreAcceso>(0);
	private Set<Ventaja> ventajas = new HashSet<Ventaja>(0);

	public Personaje() {
	}

	public Personaje(int idPersonaje, Categoria categoria, Raza raza, String nombre) {
		this.idPersonaje = idPersonaje;
		this.categoria = categoria;
		this.raza = raza;
		this.nombre = nombre;
	}

	public Personaje(int idPersonaje, Categoria categoria, Raza raza, String armaConocida, String nombre, Integer edad,
			Integer apariencia, Integer nivel, String descripcion, String particularidades, String objetivos,
			String historia, String equipoCombate, String vestimentaAccesorios, String equipoVariado, String contactos,
			String titulosPosesiones, String monedasOro, String monedasPlata, String monedasCobre, String joyas,
			String origen, String etnia, String imagen, Integer cansancioEspecial, Integer regeneracionEspecial,
			Integer pvEspecial, Integer turnoEspecial, Integer cvInvertido,
			PdsSecundariasSubterfugio pdsSecundariasSubterfugio, PdsSecundariasPerceptivas pdsSecundariasPerceptivas,
			PdsPrimariasKi pdsPrimariasKi, PdsSecundariasCreativas pdsSecundariasCreativas,
			PdsSecundariasVigor pdsSecundariasVigor, Set<Armadura> armaduras, Set<Arma> armas,
			Set<Desventaja> desventajas, Set<TablaPsiquico> tablaPsiquicos,
			Set<TablaTablaViasMagiaPersonaje> tablaTablaViasMagiaPersonajes,
			PdsPrimariasPsiquicas pdsPrimariasPsiquicas, PdsSecundariasAtleticas pdsSecundariasAtleticas,
			PdsPrimariasMisticas pdsPrimariasMisticas, PdsSecundariasSociales pdsSecundariasSociales,
			Set<TablaMagia> tablaMagias, Set<ArteMarcial> arteMarcials, Caracteristicas caracteristicas,
			PdsPrimariasComunes pdsPrimariasComunes, PdsSecundariasIntelectuales pdsSecundariasIntelectuales,
			Set<TablaEstilo> tablaEstilos, Set<PoderPsiquico> poderPsiquicos,
			Set<TablaConjurosLibreAcceso> tablaConjurosLibreAccesos, Set<Ventaja> ventajas) {
		this.idPersonaje = idPersonaje;
		this.categoria = categoria;
		this.raza = raza;
		this.armaConocida = armaConocida;
		this.nombre = nombre;
		this.edad = edad;
		this.apariencia = apariencia;
		this.nivel = nivel;
		this.descripcion = descripcion;
		this.particularidades = particularidades;
		this.objetivos = objetivos;
		this.historia = historia;
		this.equipoCombate = equipoCombate;
		this.vestimentaAccesorios = vestimentaAccesorios;
		this.equipoVariado = equipoVariado;
		this.contactos = contactos;
		this.titulosPosesiones = titulosPosesiones;
		this.monedasOro = monedasOro;
		this.monedasPlata = monedasPlata;
		this.monedasCobre = monedasCobre;
		this.joyas = joyas;
		this.origen = origen;
		this.etnia = etnia;
		this.imagen = imagen;
		this.cansancioEspecial = cansancioEspecial;
		this.regeneracionEspecial = regeneracionEspecial;
		this.pvEspecial = pvEspecial;
		this.turnoEspecial = turnoEspecial;
		this.cvInvertido = cvInvertido;
		this.pdsSecundariasSubterfugio = pdsSecundariasSubterfugio;
		this.pdsSecundariasPerceptivas = pdsSecundariasPerceptivas;
		this.pdsPrimariasKi = pdsPrimariasKi;
		this.pdsSecundariasCreativas = pdsSecundariasCreativas;
		this.pdsSecundariasVigor = pdsSecundariasVigor;
		this.armaduras = armaduras;
		this.armas = armas;
		this.desventajas = desventajas;
		this.tablaPsiquicos = tablaPsiquicos;
		this.tablaTablaViasMagiaPersonajes = tablaTablaViasMagiaPersonajes;
		this.pdsPrimariasPsiquicas = pdsPrimariasPsiquicas;
		this.pdsSecundariasAtleticas = pdsSecundariasAtleticas;
		this.pdsPrimariasMisticas = pdsPrimariasMisticas;
		this.pdsSecundariasSociales = pdsSecundariasSociales;
		this.tablaMagias = tablaMagias;
		this.arteMarcials = arteMarcials;
		this.caracteristicas = caracteristicas;
		this.pdsPrimariasComunes = pdsPrimariasComunes;
		this.pdsSecundariasIntelectuales = pdsSecundariasIntelectuales;
		this.tablaEstilos = tablaEstilos;
		this.poderPsiquicos = poderPsiquicos;
		this.tablaConjurosLibreAccesos = tablaConjurosLibreAccesos;
		this.ventajas = ventajas;
	}

	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "ID_PERSONAJE", unique = true, nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_CATEGORIA", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_RAZA", nullable = false)
	public Raza getRaza() {
		return this.raza;
	}

	public void setRaza(Raza raza) {
		this.raza = raza;
	}

	@Column(name = "ARMA_CONOCIDA", length = 100)
	public String getArmaConocida() {
		return this.armaConocida;
	}

	public void setArmaConocida(String armaConocida) {
		this.armaConocida = armaConocida;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "EDAD")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "APARIENCIA")
	public Integer getApariencia() {
		return this.apariencia;
	}

	public void setApariencia(Integer apariencia) {
		this.apariencia = apariencia;
	}

	@Column(name = "NIVEL")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "DESCRIPCION", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "PARTICULARIDADES", length = 65535)
	public String getParticularidades() {
		return this.particularidades;
	}

	public void setParticularidades(String particularidades) {
		this.particularidades = particularidades;
	}

	@Column(name = "OBJETIVOS", length = 65535)
	public String getObjetivos() {
		return this.objetivos;
	}

	public void setObjetivos(String objetivos) {
		this.objetivos = objetivos;
	}

	@Column(name = "HISTORIA", length = 65535)
	public String getHistoria() {
		return this.historia;
	}

	public void setHistoria(String historia) {
		this.historia = historia;
	}

	@Column(name = "EQUIPO_COMBATE", length = 65535)
	public String getEquipoCombate() {
		return this.equipoCombate;
	}

	public void setEquipoCombate(String equipoCombate) {
		this.equipoCombate = equipoCombate;
	}

	@Column(name = "VESTIMENTA_ACCESORIOS", length = 65535)
	public String getVestimentaAccesorios() {
		return this.vestimentaAccesorios;
	}

	public void setVestimentaAccesorios(String vestimentaAccesorios) {
		this.vestimentaAccesorios = vestimentaAccesorios;
	}

	@Column(name = "EQUIPO_VARIADO", length = 65535)
	public String getEquipoVariado() {
		return this.equipoVariado;
	}

	public void setEquipoVariado(String equipoVariado) {
		this.equipoVariado = equipoVariado;
	}

	@Column(name = "CONTACTOS", length = 65535)
	public String getContactos() {
		return this.contactos;
	}

	public void setContactos(String contactos) {
		this.contactos = contactos;
	}

	@Column(name = "TITULOS_POSESIONES", length = 65535)
	public String getTitulosPosesiones() {
		return this.titulosPosesiones;
	}

	public void setTitulosPosesiones(String titulosPosesiones) {
		this.titulosPosesiones = titulosPosesiones;
	}

	@Column(name = "MONEDAS_ORO", length = 65535)
	public String getMonedasOro() {
		return this.monedasOro;
	}

	public void setMonedasOro(String monedasOro) {
		this.monedasOro = monedasOro;
	}

	@Column(name = "MONEDAS_PLATA", length = 65535)
	public String getMonedasPlata() {
		return this.monedasPlata;
	}

	public void setMonedasPlata(String monedasPlata) {
		this.monedasPlata = monedasPlata;
	}

	@Column(name = "MONEDAS_COBRE", length = 65535)
	public String getMonedasCobre() {
		return this.monedasCobre;
	}

	public void setMonedasCobre(String monedasCobre) {
		this.monedasCobre = monedasCobre;
	}

	@Column(name = "JOYAS", length = 65535)
	public String getJoyas() {
		return this.joyas;
	}

	public void setJoyas(String joyas) {
		this.joyas = joyas;
	}

	@Column(name = "ORIGEN", length = 50)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "ETNIA", length = 50)
	public String getEtnia() {
		return this.etnia;
	}

	public void setEtnia(String etnia) {
		this.etnia = etnia;
	}

	@Column(name = "IMAGEN", length = 250)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "CANSANCIO_ESPECIAL")
	public Integer getCansancioEspecial() {
		return this.cansancioEspecial;
	}

	public void setCansancioEspecial(Integer cansancioEspecial) {
		this.cansancioEspecial = cansancioEspecial;
	}

	@Column(name = "REGENERACION_ESPECIAL")
	public Integer getRegeneracionEspecial() {
		return this.regeneracionEspecial;
	}

	public void setRegeneracionEspecial(Integer regeneracionEspecial) {
		this.regeneracionEspecial = regeneracionEspecial;
	}

	@Column(name = "PV_ESPECIAL")
	public Integer getPvEspecial() {
		return this.pvEspecial;
	}

	public void setPvEspecial(Integer pvEspecial) {
		this.pvEspecial = pvEspecial;
	}

	@Column(name = "TURNO_ESPECIAL")
	public Integer getTurnoEspecial() {
		return this.turnoEspecial;
	}

	public void setTurnoEspecial(Integer turnoEspecial) {
		this.turnoEspecial = turnoEspecial;
	}

	@Column(name = "CV_INVERTIDO")
	public Integer getCvInvertido() {
		return this.cvInvertido;
	}

	public void setCvInvertido(Integer cvInvertido) {
		this.cvInvertido = cvInvertido;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsSecundariasSubterfugio getPdsSecundariasSubterfugio() {
		return this.pdsSecundariasSubterfugio;
	}

	public void setPdsSecundariasSubterfugio(PdsSecundariasSubterfugio pdsSecundariasSubterfugio) {
		this.pdsSecundariasSubterfugio = pdsSecundariasSubterfugio;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsSecundariasPerceptivas getPdsSecundariasPerceptivas() {
		return this.pdsSecundariasPerceptivas;
	}

	public void setPdsSecundariasPerceptivas(PdsSecundariasPerceptivas pdsSecundariasPerceptivas) {
		this.pdsSecundariasPerceptivas = pdsSecundariasPerceptivas;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsPrimariasKi getPdsPrimariasKi() {
		return this.pdsPrimariasKi;
	}

	public void setPdsPrimariasKi(PdsPrimariasKi pdsPrimariasKi) {
		this.pdsPrimariasKi = pdsPrimariasKi;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsSecundariasCreativas getPdsSecundariasCreativas() {
		return this.pdsSecundariasCreativas;
	}

	public void setPdsSecundariasCreativas(PdsSecundariasCreativas pdsSecundariasCreativas) {
		this.pdsSecundariasCreativas = pdsSecundariasCreativas;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsSecundariasVigor getPdsSecundariasVigor() {
		return this.pdsSecundariasVigor;
	}

	public void setPdsSecundariasVigor(PdsSecundariasVigor pdsSecundariasVigor) {
		this.pdsSecundariasVigor = pdsSecundariasVigor;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<Armadura> getArmaduras() {
		return this.armaduras;
	}

	public void setArmaduras(Set<Armadura> armaduras) {
		this.armaduras = armaduras;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<Arma> getArmas() {
		return this.armas;
	}

	public void setArmas(Set<Arma> armas) {
		this.armas = armas;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<Desventaja> getDesventajas() {
		return this.desventajas;
	}

	public void setDesventajas(Set<Desventaja> desventajas) {
		this.desventajas = desventajas;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<TablaPsiquico> getTablaPsiquicos() {
		return this.tablaPsiquicos;
	}

	public void setTablaPsiquicos(Set<TablaPsiquico> tablaPsiquicos) {
		this.tablaPsiquicos = tablaPsiquicos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "personaje")
	public Set<TablaTablaViasMagiaPersonaje> getTablaTablaViasMagiaPersonajes() {
		return this.tablaTablaViasMagiaPersonajes;
	}

	public void setTablaTablaViasMagiaPersonajes(Set<TablaTablaViasMagiaPersonaje> tablaTablaViasMagiaPersonajes) {
		this.tablaTablaViasMagiaPersonajes = tablaTablaViasMagiaPersonajes;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsPrimariasPsiquicas getPdsPrimariasPsiquicas() {
		return this.pdsPrimariasPsiquicas;
	}

	public void setPdsPrimariasPsiquicas(PdsPrimariasPsiquicas pdsPrimariasPsiquicas) {
		this.pdsPrimariasPsiquicas = pdsPrimariasPsiquicas;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsSecundariasAtleticas getPdsSecundariasAtleticas() {
		return this.pdsSecundariasAtleticas;
	}

	public void setPdsSecundariasAtleticas(PdsSecundariasAtleticas pdsSecundariasAtleticas) {
		this.pdsSecundariasAtleticas = pdsSecundariasAtleticas;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsPrimariasMisticas getPdsPrimariasMisticas() {
		return this.pdsPrimariasMisticas;
	}

	public void setPdsPrimariasMisticas(PdsPrimariasMisticas pdsPrimariasMisticas) {
		this.pdsPrimariasMisticas = pdsPrimariasMisticas;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsSecundariasSociales getPdsSecundariasSociales() {
		return this.pdsSecundariasSociales;
	}

	public void setPdsSecundariasSociales(PdsSecundariasSociales pdsSecundariasSociales) {
		this.pdsSecundariasSociales = pdsSecundariasSociales;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<TablaMagia> getTablaMagias() {
		return this.tablaMagias;
	}

	public void setTablaMagias(Set<TablaMagia> tablaMagias) {
		this.tablaMagias = tablaMagias;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<ArteMarcial> getArteMarcials() {
		return this.arteMarcials;
	}

	public void setArteMarcials(Set<ArteMarcial> arteMarcials) {
		this.arteMarcials = arteMarcials;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public Caracteristicas getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(Caracteristicas caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsPrimariasComunes getPdsPrimariasComunes() {
		return this.pdsPrimariasComunes;
	}

	public void setPdsPrimariasComunes(PdsPrimariasComunes pdsPrimariasComunes) {
		this.pdsPrimariasComunes = pdsPrimariasComunes;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "personaje")
	public PdsSecundariasIntelectuales getPdsSecundariasIntelectuales() {
		return this.pdsSecundariasIntelectuales;
	}

	public void setPdsSecundariasIntelectuales(PdsSecundariasIntelectuales pdsSecundariasIntelectuales) {
		this.pdsSecundariasIntelectuales = pdsSecundariasIntelectuales;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<TablaEstilo> getTablaEstilos() {
		return this.tablaEstilos;
	}

	public void setTablaEstilos(Set<TablaEstilo> tablaEstilos) {
		this.tablaEstilos = tablaEstilos;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<PoderPsiquico> getPoderPsiquicos() {
		return this.poderPsiquicos;
	}

	public void setPoderPsiquicos(Set<PoderPsiquico> poderPsiquicos) {
		this.poderPsiquicos = poderPsiquicos;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<TablaConjurosLibreAcceso> getTablaConjurosLibreAccesos() {
		return this.tablaConjurosLibreAccesos;
	}

	public void setTablaConjurosLibreAccesos(Set<TablaConjurosLibreAcceso> tablaConjurosLibreAccesos) {
		this.tablaConjurosLibreAccesos = tablaConjurosLibreAccesos;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "personajes")
	public Set<Ventaja> getVentajas() {
		return this.ventajas;
	}

	public void setVentajas(Set<Ventaja> ventajas) {
		this.ventajas = ventajas;
	}

}
