package modelo;
// Generated 15 jun. 2021 0:01:59 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * PoderPsiquico generated by hbm2java
 */
@Entity
@Table(name = "poder_psiquico", catalog = "anima_sheets_data")
public class PoderPsiquico implements java.io.Serializable {

	private Integer idPoderPsiquico;
	private String nombre;
	private String descripcion;
	private String disciplina;
	private int nivel;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public PoderPsiquico() {
	}

	public PoderPsiquico(String nombre, String descripcion, String disciplina, int nivel) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.disciplina = disciplina;
		this.nivel = nivel;
	}

	public PoderPsiquico(String nombre, String descripcion, String disciplina, int nivel, Set<Personaje> personajes) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.disciplina = disciplina;
		this.nivel = nivel;
		this.personajes = personajes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PODER_PSIQUICO", unique = true, nullable = false)
	public Integer getIdPoderPsiquico() {
		return this.idPoderPsiquico;
	}

	public void setIdPoderPsiquico(Integer idPoderPsiquico) {
		this.idPoderPsiquico = idPoderPsiquico;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DISCIPLINA", nullable = false, length = 250)
	public String getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(String disciplina) {
		this.disciplina = disciplina;
	}

	@Column(name = "NIVEL", nullable = false)
	public int getNivel() {
		return this.nivel;
	}

	public void setNivel(int nivel) {
		this.nivel = nivel;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tabla_poder_psiquico_personaje", catalog = "anima_sheets_data", joinColumns = {
			@JoinColumn(name = "ID_PODER_PSIQUICO", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_PERSONAJE", nullable = false, updatable = false) })
	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

}
