package modelo;
// Generated 24 may. 2021 13:40:54 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Raza generated by hbm2java
 */
@Entity
@Table(name = "raza", catalog = "anima_sheets_data")
public class Raza implements java.io.Serializable {

	private Integer idRaza;
	private String nombre;
	private String descripcion;
	private String rasgo1;
	private String rasgo2;
	private String rasgo3;
	private String rasgo4;
	private String rasgo5;
	private String rasgo6;
	private String rasgo7;
	private String rasgo8;
	private String rasgo9;
	private String rasgo10;
	private String rasgo11;
	private Integer modificadorNivel;
	private String imagen;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public Raza() {
	}

	public Raza(String nombre, String descripcion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Raza(String nombre, String descripcion, String rasgo1, String rasgo2, String rasgo3, String rasgo4,
			String rasgo5, String rasgo6, String rasgo7, String rasgo8, String rasgo9, String rasgo10, String rasgo11,
			Integer modificadorNivel, String imagen, Set<Personaje> personajes) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.rasgo1 = rasgo1;
		this.rasgo2 = rasgo2;
		this.rasgo3 = rasgo3;
		this.rasgo4 = rasgo4;
		this.rasgo5 = rasgo5;
		this.rasgo6 = rasgo6;
		this.rasgo7 = rasgo7;
		this.rasgo8 = rasgo8;
		this.rasgo9 = rasgo9;
		this.rasgo10 = rasgo10;
		this.rasgo11 = rasgo11;
		this.modificadorNivel = modificadorNivel;
		this.imagen = imagen;
		this.personajes = personajes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_RAZA", unique = true, nullable = false)
	public Integer getIdRaza() {
		return this.idRaza;
	}

	public void setIdRaza(Integer idRaza) {
		this.idRaza = idRaza;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "RASGO1", length = 65535)
	public String getRasgo1() {
		return this.rasgo1;
	}

	public void setRasgo1(String rasgo1) {
		this.rasgo1 = rasgo1;
	}

	@Column(name = "RASGO2", length = 65535)
	public String getRasgo2() {
		return this.rasgo2;
	}

	public void setRasgo2(String rasgo2) {
		this.rasgo2 = rasgo2;
	}

	@Column(name = "RASGO3", length = 65535)
	public String getRasgo3() {
		return this.rasgo3;
	}

	public void setRasgo3(String rasgo3) {
		this.rasgo3 = rasgo3;
	}

	@Column(name = "RASGO4", length = 65535)
	public String getRasgo4() {
		return this.rasgo4;
	}

	public void setRasgo4(String rasgo4) {
		this.rasgo4 = rasgo4;
	}

	@Column(name = "RASGO5", length = 65535)
	public String getRasgo5() {
		return this.rasgo5;
	}

	public void setRasgo5(String rasgo5) {
		this.rasgo5 = rasgo5;
	}

	@Column(name = "RASGO6", length = 65535)
	public String getRasgo6() {
		return this.rasgo6;
	}

	public void setRasgo6(String rasgo6) {
		this.rasgo6 = rasgo6;
	}

	@Column(name = "RASGO7", length = 65535)
	public String getRasgo7() {
		return this.rasgo7;
	}

	public void setRasgo7(String rasgo7) {
		this.rasgo7 = rasgo7;
	}

	@Column(name = "RASGO8", length = 65535)
	public String getRasgo8() {
		return this.rasgo8;
	}

	public void setRasgo8(String rasgo8) {
		this.rasgo8 = rasgo8;
	}

	@Column(name = "RASGO9", length = 65535)
	public String getRasgo9() {
		return this.rasgo9;
	}

	public void setRasgo9(String rasgo9) {
		this.rasgo9 = rasgo9;
	}

	@Column(name = "RASGO10", length = 65535)
	public String getRasgo10() {
		return this.rasgo10;
	}

	public void setRasgo10(String rasgo10) {
		this.rasgo10 = rasgo10;
	}

	@Column(name = "RASGO11", length = 65535)
	public String getRasgo11() {
		return this.rasgo11;
	}

	public void setRasgo11(String rasgo11) {
		this.rasgo11 = rasgo11;
	}

	@Column(name = "MODIFICADOR_NIVEL")
	public Integer getModificadorNivel() {
		return this.modificadorNivel;
	}

	public void setModificadorNivel(Integer modificadorNivel) {
		this.modificadorNivel = modificadorNivel;
	}

	@Column(name = "IMAGEN", length = 50)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "raza")
	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

}
