package modelo;
// Generated 22 may. 2021 19:31:55 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TablaVentajaPersonajeId generated by hbm2java
 */
@Embeddable
public class TablaVentajaPersonajeId implements java.io.Serializable {

	private int idVentaja;
	private int idPersonaje;

	public TablaVentajaPersonajeId() {
	}

	public TablaVentajaPersonajeId(int idVentaja, int idPersonaje) {
		this.idVentaja = idVentaja;
		this.idPersonaje = idPersonaje;
	}

	@Column(name = "ID_VENTAJA", nullable = false)
	public int getIdVentaja() {
		return this.idVentaja;
	}

	public void setIdVentaja(int idVentaja) {
		this.idVentaja = idVentaja;
	}

	@Column(name = "ID_PERSONAJE", nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TablaVentajaPersonajeId))
			return false;
		TablaVentajaPersonajeId castOther = (TablaVentajaPersonajeId) other;

		return (this.getIdVentaja() == castOther.getIdVentaja())
				&& (this.getIdPersonaje() == castOther.getIdPersonaje());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVentaja();
		result = 37 * result + this.getIdPersonaje();
		return result;
	}

}
