package modelo;
// Generated 13 jun. 2021 23:25:16 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TablaTablaViasMagiaPersonaje generated by hbm2java
 */
@Entity
@Table(name = "tabla_tabla_vias_magia_personaje", catalog = "anima_sheets_data")
public class TablaTablaViasMagiaPersonaje implements java.io.Serializable {

	private TablaTablaViasMagiaPersonajeId id;
	private Personaje personaje;
	private TablaViasMagia tablaViasMagia;
	private Integer nivelesUsados;

	public TablaTablaViasMagiaPersonaje() {
	}

	public TablaTablaViasMagiaPersonaje(TablaTablaViasMagiaPersonajeId id, Personaje personaje,
			TablaViasMagia tablaViasMagia) {
		this.id = id;
		this.personaje = personaje;
		this.tablaViasMagia = tablaViasMagia;
	}

	public TablaTablaViasMagiaPersonaje(TablaTablaViasMagiaPersonajeId id, Personaje personaje,
			TablaViasMagia tablaViasMagia, Integer nivelesUsados) {
		this.id = id;
		this.personaje = personaje;
		this.tablaViasMagia = tablaViasMagia;
		this.nivelesUsados = nivelesUsados;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idVia", column = @Column(name = "ID_VIA", nullable = false)),
			@AttributeOverride(name = "idPersonaje", column = @Column(name = "ID_PERSONAJE", nullable = false)) })
	public TablaTablaViasMagiaPersonajeId getId() {
		return this.id;
	}

	public void setId(TablaTablaViasMagiaPersonajeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONAJE", nullable = false, insertable = false, updatable = false)
	public Personaje getPersonaje() {
		return this.personaje;
	}

	public void setPersonaje(Personaje personaje) {
		this.personaje = personaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_VIA", nullable = false, insertable = false, updatable = false)
	public TablaViasMagia getTablaViasMagia() {
		return this.tablaViasMagia;
	}

	public void setTablaViasMagia(TablaViasMagia tablaViasMagia) {
		this.tablaViasMagia = tablaViasMagia;
	}

	@Column(name = "NIVELES_USADOS")
	public Integer getNivelesUsados() {
		return this.nivelesUsados;
	}

	public void setNivelesUsados(Integer nivelesUsados) {
		this.nivelesUsados = nivelesUsados;
	}

}
