package modelo;
// Generated 22 may. 2021 19:31:55 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TablaDesventajaPersonajeId generated by hbm2java
 */
@Embeddable
public class TablaDesventajaPersonajeId implements java.io.Serializable {

	private int idDesventaja;
	private int idPersonaje;

	public TablaDesventajaPersonajeId() {
	}

	public TablaDesventajaPersonajeId(int idDesventaja, int idPersonaje) {
		this.idDesventaja = idDesventaja;
		this.idPersonaje = idPersonaje;
	}

	@Column(name = "ID_DESVENTAJA", nullable = false)
	public int getIdDesventaja() {
		return this.idDesventaja;
	}

	public void setIdDesventaja(int idDesventaja) {
		this.idDesventaja = idDesventaja;
	}

	@Column(name = "ID_PERSONAJE", nullable = false)
	public int getIdPersonaje() {
		return this.idPersonaje;
	}

	public void setIdPersonaje(int idPersonaje) {
		this.idPersonaje = idPersonaje;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TablaDesventajaPersonajeId))
			return false;
		TablaDesventajaPersonajeId castOther = (TablaDesventajaPersonajeId) other;

		return (this.getIdDesventaja() == castOther.getIdDesventaja())
				&& (this.getIdPersonaje() == castOther.getIdPersonaje());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDesventaja();
		result = 37 * result + this.getIdPersonaje();
		return result;
	}

}
