package modelo;
// Generated 15 jun. 2021 23:20:51 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tamano generated by hbm2java
 */
@Entity
@Table(name = "tamano", catalog = "anima_sheets_data")
public class Tamano implements java.io.Serializable {

	private int idTamano;
	private String medida;
	private BigDecimal multiplicador;
	private int puntosFuerzaExtra;
	private int incrementoEntereza;
	private int incrementoRotura;
	private Set<ArmaPersonaje> armaPersonajes = new HashSet<ArmaPersonaje>(0);

	public Tamano() {
	}

	public Tamano(int idTamano, String medida, BigDecimal multiplicador, int puntosFuerzaExtra, int incrementoEntereza,
			int incrementoRotura) {
		this.idTamano = idTamano;
		this.medida = medida;
		this.multiplicador = multiplicador;
		this.puntosFuerzaExtra = puntosFuerzaExtra;
		this.incrementoEntereza = incrementoEntereza;
		this.incrementoRotura = incrementoRotura;
	}

	public Tamano(int idTamano, String medida, BigDecimal multiplicador, int puntosFuerzaExtra, int incrementoEntereza,
			int incrementoRotura, Set<ArmaPersonaje> armaPersonajes) {
		this.idTamano = idTamano;
		this.medida = medida;
		this.multiplicador = multiplicador;
		this.puntosFuerzaExtra = puntosFuerzaExtra;
		this.incrementoEntereza = incrementoEntereza;
		this.incrementoRotura = incrementoRotura;
		this.armaPersonajes = armaPersonajes;
	}

	@Id

	@Column(name = "ID_TAMANO", unique = true, nullable = false)
	public int getIdTamano() {
		return this.idTamano;
	}

	public void setIdTamano(int idTamano) {
		this.idTamano = idTamano;
	}

	@Column(name = "MEDIDA", nullable = false, length = 50)
	public String getMedida() {
		return this.medida;
	}

	public void setMedida(String medida) {
		this.medida = medida;
	}

	@Column(name = "MULTIPLICADOR", nullable = false, precision = 2)
	public BigDecimal getMultiplicador() {
		return this.multiplicador;
	}

	public void setMultiplicador(BigDecimal multiplicador) {
		this.multiplicador = multiplicador;
	}

	@Column(name = "PUNTOS_FUERZA_EXTRA", nullable = false)
	public int getPuntosFuerzaExtra() {
		return this.puntosFuerzaExtra;
	}

	public void setPuntosFuerzaExtra(int puntosFuerzaExtra) {
		this.puntosFuerzaExtra = puntosFuerzaExtra;
	}

	@Column(name = "INCREMENTO_ENTEREZA", nullable = false)
	public int getIncrementoEntereza() {
		return this.incrementoEntereza;
	}

	public void setIncrementoEntereza(int incrementoEntereza) {
		this.incrementoEntereza = incrementoEntereza;
	}

	@Column(name = "INCREMENTO_ROTURA", nullable = false)
	public int getIncrementoRotura() {
		return this.incrementoRotura;
	}

	public void setIncrementoRotura(int incrementoRotura) {
		this.incrementoRotura = incrementoRotura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tamano")
	public Set<ArmaPersonaje> getArmaPersonajes() {
		return this.armaPersonajes;
	}

	public void setArmaPersonajes(Set<ArmaPersonaje> armaPersonajes) {
		this.armaPersonajes = armaPersonajes;
	}

}
